### ISSUE TITLE
Your dataset needs at least one column.

### ISSUE THREAD

**Issue by PMassicotte** [fstpackage/fst#102]
I was interested to use this package to save large datasets. However, I am getting this error when trying to create a simple benchmark.

``` r
                                                      
df <- data.frame(matrix(runif(256*65536), nrow = 256))
                                                      
file <- tempfile(fileext = ".fst")                    
                                                      
system.time(fst::write.fst(df, file))                 
#> Error in fstStore(path, x, as.integer(compress)): Your dataset needs at least one column.
#> Timing stopped at: 0.044 0 0.045
```

**Comment by MarcusKlik** [comment]
Hi @PMassicotte, thanks for reporting your issue! The error you are getting has been resolved in the `dev` version of `fst` which will be on CRAN soon, you can install the latest `dev` using:

```r
devtools::install_github("fstpackage/fst", ref = "develop")
```

I did a quick benchmark using your random data-set:

``` r
benchmark <- function(nr_of_rows) {
  df <- data.frame(matrix(runif(2^26), nrow = nr_of_rows))

  # reduce change of garbage collection and activate disk if sleeping
  gc()
  saveRDS("warmup", "warmup.rds")

  # microbenchmark for more accurate timings
  timings <- microbenchmark::microbenchmark(
    fst::write_fst(df, "1.fst", 1),
    times = 1
  )

  1000 * as.numeric(object.size(df)) / median(timings$time)  # speed in MB/s
}


benchmark(256)
#> [1]  175.6385
```

as you can see, the speed is relatively low. That's because `fst` stores it's data in 32kB blocks. When there are only 256 rows, these block are used very ineffectively (`fst` is optimized for large number of rows but not for a large number of columns)

The numbers change when the row size is increased:

```r
benchmark(65536)
#> [1] 1084.514

benchmark(2^25)
#> [1] 1641.623
```

when your data-set is rescaled to 'only' 10 columns, the speed goes up to ~1.6 GB/s in this example (I'm not using compression because random doubles are very hard to compress effectively). This speed is around the maximum I can get out of the SSD drive on the laptop I'm currently using.

For the complete picture:

```r
res <- sapply(8:26, function(power) {
  number_of_rows <- 2 ^ power
  benchmark(number_of_rows)
})

library(ggplot2)

ggplot(data.frame(Rows = 2 ^ (8:26), Speed = res)) +
  geom_point(aes(Rows, Speed)) +
  geom_smooth(aes(Rows, Speed)) +
  scale_x_log10()
```

![image](https://user-images.githubusercontent.com/24658401/32863708-af5eb96e-ca5c-11e7-952f-5f465cd0cbc4.png)

There is not much statistics here (only single measurements for each point) but the general pattern is clear, `fst` is optimized for (and gets faster with) larger data-sets.

Hope that helps you!

**Comment by PMassicotte** [comment]
Thank you @MarcusKlik! This is nice to see. Of course my example with 65536 columns might not be realistic. I will give it a try with the dev version tomorrow on real data. Thank for your help.

**Comment by MarcusKlik** [comment]
great, if you have some benchmark results later, I would be very interested to see them. If you want you could post them here! 

thanks
