### ISSUE TITLE
Magic number?

### ISSUE THREAD

**Issue by davidanthoff** [fstpackage/fst#105]
Do fst files have a magic number that I could check to make sure a given file is actually a fst file?

**Comment by MarcusKlik** [comment]
hi @davidanthoff , thanks for a very interesting question!

The current CRAN version doesn't have a magic number, but the next release will. All meta information in the _latest_ `fst` format is now hashed with a _magic number_. So, you could use any of these meta-data blocks to test if you're dealing with a `fst` file.

For example, you could use the header information:

``` r

is_fst <- function(path) {

  zz <- file(path, "rb")  # open file in binary mode

  # read the header hash value (two integers)
  header_hash <- readBin(zz, integer(), 2)

  # read the 40-bytes 'table' header
  fst_header <- readBin(zz, raw(), 40)

  close(zz)

  # calculate the header hash manually
  hash_value <- fst::hash_fst(fst_header)

  return (sum(hash_value != header_hash) == 0)
}

# generate some sample files
df <- data.frame(X = 1:10)
fst::write.fst(df, "some_fst_file.fst")
write.csv2(df, "some_csv_file.csv")

# test magic number
is_fst("some_fst_file.fst")
#> [1] TRUE
is_fst("some_csv_file.csv")
#> [1] FALSE
```

So, you can use method `hash_fst` to calculate a 64-bit hash using the  `xxHash` algorithm. If you don't specify a _seed_, a default value for _seed_ is used. That value can be considered as a _magic number_ for the `fst` format, because it's used everywhere to hash or mark data.

I realize that the `is_fst` method above is not very obvious to the average package user (:-)), would it be useful to add a method `is_fst` to the package?

**Comment by davidanthoff** [comment]
We are working on integration for julia, and there is a uniform file loading API where you can just write
````julia
using FileIO

load("filename.fst")
````
and it will automatically pick the correct package to load that file, based on either just the file extension, or (better) based on the file extension and a magic byte. Given that the ``*.fst`` file extension is used by at least two other file formats, we are a bit hesitant to just blanket assume that every ``*.fst`` file is in the format of this package here.

By far the easiest solution would be if the file format just had a sequence of magic bytes at a known offset, without any further computations. I think a lot of file formats have that, and it really helps in these kind of situations. So my ideal situation would be if you told me: "we always have the byte sequence X at offset Y" in fst files. That would be super easy to integrate.

I assume the file extension is probably set in stone at this point, but something longer with no name conflict with other file formats would obviously also fantastic (e.g. Feather uses the ``*.feather`` extension). But I totally understand that this might be too big of an ask at this point.

I think there might also be some way to use something like the hash function that you describe here with FileIO.jl, but I'll have to investigate that a bit more.

**Comment by MarcusKlik** [comment]
Hi @davidanthoff, that's a great idea! I see your point in that it is very cumbersome to run a hash calculation just to check a file format :-)

The format is complete but I kept [a few free bytes](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/fststore.cpp#L56-L61) in the header meta-data just in case. So I could use those to insert a magic number for `fst`.

A few questions you might be able to answer:

* In your experience, is a 32-bit value sufficient as a magic number or would you advise a 64-bit value?
* Would it be convenient to have a byte-symmetric value, so that it can be read from both little-endian and big-endian systems?
* Is there a list somewhere with magic numbers, to avoid selecting a number that's already used (although the chances of that are pretty slim with even 32 bits :-))

thanks a lot!

**Comment by MarcusKlik** [comment]
Ah, I see a lot of numbers are already documented, for example [here](https://en.wikipedia.org/wiki/List_of_file_signatures). Many are 32-bit, but larger signatures are also used.

**Comment by davidanthoff** [comment]
Hehe, always good to leave some space :)

I'm not really an expert on these questions in general, I'm afraid. I think for our julia use-case, 32 bits would be fine because the detection algorithm would essentially be file extension + magic number, so unless you pick exactly the same magic number as the two other file formats with the same extension, we should be good. I don't think we need the symmetric magic byte, as long as the bit pattern is always exactly the same, independent of whether the file was generated on a little- or big-endian system.

**Comment by MarcusKlik** [comment]
Ha, indeed :-) So I guess using the same philosophy I will still keep 4 free bytes and use 4 to store the magic number! About the format:

* byte 17-20 in the format have been set to hexadecimal number `0x50414150`
* these 4 bytes can be read as a single integer  number equal to `1346453840`
* those statements hold for both little-endian and big-endian systems, because that magic number is _byte-symmetric_
* The first two bytes (`0x50` and `0x41`) are equal to the _Apache Parquet columnar file format_, perhaps just to start of a new family of columnar file formats :-)

Hope that helps you, the complete fst header summary can be found [in this code](https://github.com/fstpackage/fstlib/blob/master/lib/interface/fststore.cpp#L51-L62)

best regards and good luck with your Julia package, if you need anything there please let me know!

**Comment by MarcusKlik** [comment]
Hi @davidanthoff, the magic number will only be present in `fst` files generated from the C++ `fstlib` library version 1 and higher (which is included in the next CRAN release of the `fst` package and the current `dev` version).

That means that you won't be able to detect 'old' `fst` files with the magic number (this lack of a well defined signature is also one of the main reasons why the 'old' beta format will not be supported anymore eventually).

**Comment by davidanthoff** [comment]
Yeah, I think that is fine. Do you have a rough timeline for releasing the next fst version?

**Comment by MarcusKlik** [comment]
Hi @davidanthoff, I'm aiming for next week :-)

I considered the magic number location in the format some more and should probably move it up to [byte position 44-48](https://github.com/fstpackage/fstlib/blob/master/lib/interface/fststore.cpp#L62|)

Then the 8-byte slot is available for future purposes (and can fit 64-bit position information for example). I will make sure that change is committed later this day!

**Comment by MarcusKlik** [comment]
Hi @davidanthoff, the magic number has been moved to byte position 44, the complete header is now defined as follows:

|  byte    | type | description |
| -------  |:----------------------:| :-----------------------:|
| 0 - 7     | unsigned long long | hash of table header |
| 8 - 11   | unsigned int            | fstlib version of header
| 12 - 15 | int                            | binary table flags
| 16 - 23 |                                 | free bytes for possible future use
| 24 - 27 | unsigned int            | minimum fstlib version required to read file
| 28 - 31 | int                            | total number of columns in primary chunkset
| 32 - 39 | unsigned long long | reference to the table's primary chunkset
| 40 -43  | int                            | number of keys in primary chunkset
| 44 - 47 | int                            | fst magic number (the signature of a fst file)

So the relevant bytes for you are 44 - 47 (zero based) for the magic number.
The minimum `fstlib` version (24 - 27) might also be useful. It is set to the minimal version of the `fstlib` library that is required to read all parts of the `fst` file. This version can be different from the version of the header itself because in the near future it will be possible to add rows and/or columns to an existing `fst` file. The added data can have a different (more recent) version than the header.

Thanks again!

**Comment by timholy** [comment]
Is 1346453840 little- or big-endian? https://github.com/fstpackage/fst/commit/fba29373571ff09e5b42d382710cc4b22bb49362#diff-12b68c61693d1b10d802c17bf22f5f714c248942a74b1d93af874e41b1186bc0R59

That is, is it `[0x50, 0x41, 0x41, 0x50]` or something else?

**Comment by MarcusKlik** [comment]
Hi @timholy,

thanks for asking! Because this byte sequence is symmetrical, using it on big- or little-endian systems would yield identical (32 bit) integer values:

``` r
# show bytes
pryr::bytes(as.integer(1346453840))
#> [1] "50 41 41 50"
```

to get the _magic number_ easily from `R`, you can use:

``` r
path <- tempfile(".fst")
fst::write_fst(cars, path)

# get magic number
readBin(path, "integer", 12)[12]
#> [1] 1346453840
```

hope that helps!

**Comment by timholy** [comment]
Hah, I didn't even really notice the sequence, thanks for pointing that out.
