### ISSUE TITLE
Format Complete; Format Update Function

### ISSUE THREAD

**Issue by mperone** [fstpackage/fst#106]
Hi Marcus, 

I've been following this development eagerly as it really looks like once it's ready it will be a huge upgrade to the storage options for R data. As version 0.8.0 nears though, I have 2 questions I haven't been able to answer confidently:
1) What version do you anticipate being the 'format complete' version; i.e. when can we use the library and not have to worry about our .fst files not being compatible with newer versions of the library?
2) In the interim, as the library updates and settles on the final format, will there be any functions available that will 'update' previous version .fst files to be compatible with the current library?

Thanks,
Matt

**Comment by MarcusKlik** [comment]
Hi @mperone, thanks a lot! To answer your questions:

1. The format is complete now and will not be changed anymore until the next CRAN release. So that means that  files that are generated with the latest `dev` version can be read by the next CRAN version _**and also any future version**_
2.  The next CRAN release (version 0.8.0) will still read files generated by the previous CRAN version, but the user needs to set the parameter _old_format = TRUE_. That's because the `fst` format before 0.8.0 is less secure (no hashing for example) and that version will not be supported anymore after some time (but you can always 're-save' the data off course)
3. After version 0.8.0 `fst` will be backwards compatible, so future versions will always be guaranteed to read older version (>= 0.8.0).

Hope that answers your questions and thanks for waiting!

**Comment by mperone** [comment]
Awesome. Thanks again.
