### ISSUE TITLE
Consider a `[` interface to an on disk fst?

### ISSUE THREAD

**Issue by kendonB** [fstpackage/fst#107]
The feather store object is nice as it acts kind of like a data.frame for querying subsets of the on-disk feather object.

The ``fst`` store object would have a ``[`` method that would handle row/column querying using numerics, logicals, and maybe expressions based on columns in the ``fst``.

**Comment by MarcusKlik** [comment]
Hi @kendonB, thanks for your feature request!

This feature will require a subset of features that you requested in #108 and will be added to `fst` package version `0.9.0`. The `fst` interface will be more like `data.table`'s interface for added functionality such as grouping operations.

The general idea is to supply a relatively general interface that works by reading full columns and operating on those. For simple operators and functions (`+`, `-`, `*`, `/`, `|`, `&`, `sum`, `min`, `max`, etc.), the calculations will be moved to the `C++` core library so that they can be performed in parallel with the IO (so during reading the data on background threads). This will offer much higher performance for these operators (probably at maximum disk speed for data with up to medium compression settings).

thanks and greetings!

**Comment by xiaodaigh** [comment]
[disk.frame](https://github.com/xiaodaigh/disk.frame) is one attempt to do this

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, very nice! And I like your approach of having multiple possible _back-ends_, that's very dynamic (and good for benchmarking as well :-))

Also, having an abstraction layer around multiple `fst` files is a very powerful concept. You could build _map-reduce_ like algorithms on top of that, nice work!

The ability to access multiple `fst` files as a single _table_ is on the feature list (#14), I guess that feature will be useful for your package as well?

**Comment by xiaodaigh** [comment]
@MarcusKlik Thanks for the encouragement. I think the features that will really help are #14 #91, #78 and being able to apply a simple equality filter (via indexing) would be really nice. 

For example, I was implementing a group by an algorithm using fst as the backend, so firstly I have to sort on a variable to figure out the groups, this is really easy using `read.fst(path, columns = column_to_group)` on all fst files and then sorting the result. The next step is to read through each of the original fst files again and output the content into another set of fst files so that rows that belong to the same group will be in the same output fst file; in this case, if I can append directly to disk then it will be really fast. Currently, I write a lot of small fst files and then `rbindlist` them together instead of being to append directly. So really looking forward to v0.9

Your package makes me want to learn C/C++ so I can contribute. I wish my packages are half as good as fst.

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, thanks! And no worries, the `fstlib` interface is relatively simple :-). I will start some documentation on the `C++` API soon, so that `fstlib` can easily be used in other languages as well (I think `C++`, `Python` and `Julia` to start with).

What you're describing can be done nicely using a [merge sort](https://en.wikipedia.org/wiki/Merge_sort) algorithm. If you use multiple files, you can even do the sorting in parallel, something that would be very useful because the last step in the traditional merge sort is single threaded and a real bottleneck...  My plan is to create an initial sorting algorithm that makes use of a custom sorter (so not implemented in `fstlib` but provided by the client package (`fst` in this case). That's because `data.table` already has a very fast sorting algorithm, so it would be a quick win to use that to start with!

The filtering with simple operators will come to `v0.9.0`, as will the features #91, #78 and hopefully also #14.

And no time like the present to start learning C/C++ :-)

greetings

**Comment by MarcusKlik** [comment]
A basic 'data.frame' interface was added to the package. The idea is that the user creates a reference to a `fst` file using method `fst()`. That reference can be accessed like a `data.frame`:

```r
# create sample data
df <- data.frame(
  X = 1:26,
  Y = LETTERS,
  Z = runif(26, 4, 7),
  stringsAsFactors = FALSE
)

# write to disk
write_fst(df, "1.fst")

# create a reference to the fst file
x <- fst("1.fst")


# data.frame interface to x:

as.data.frame(x, row.names = LETTERS)
as.list(x)
x$X
x$S
nrow(x)
ncol(x)
dim(x)
dimnames(x)
colnames(x)
rownames(x)
names(x)

# '[[' generic

x[["Y"]]
x[["S"]]
x[[1:2]]
x[[c(2, 4)]]
x[["G"]]

# '[' generic

x[2]
x[2.6]
x[TRUE]
x[c(1.1, 2)]
x[c(TRUE, FALSE)]
x[c(TRUE, FALSE, TRUE)]
x[]
x[2]
x[i = 2]
x[j = 2]
x[drop = FALSE]
x[,]
x[,2:3]
x[j = 2:3, drop = FALSE]
x[i = 2:1, drop = FALSE]
x[2, drop = FALSE]
x[,, drop = FALSE]
x[,,]
x[j = 2, drop = FALSE]
```

Column sub-setting is done by using the `columns` parameter in `read_fst()`. Row sub-setting is currently done by reading data between the minimum and maximum row in the selection (using `from` and `to` in `read_fst()`) and doing a additional row selection on that result. That will be further optimized in the future in the `fstlib` library, but the interface won't change because of that.

I think it will be best to implement the `dplyr` and `data.table` interface in separate _R-only_ packages. The `dplyr` interface in @krlmlr's [`fstplyr` package](https://github.com/krlmlr/fstplyr) and the `data.table` interface in a new package [`fsttable`](https://github.com/fstpackage/fsttable). That way, `fst` can provide a universal interface for dependent packages to do (parallel) selections and computations on `fst` files, but the actual interface to the user is left to the dependent packages. That's a clear separation of concerns:  OpenMP, C++, compression and algorithm related issues can be tackled in the `fst` package and interface related issues in the dependent packages. Updates and (speed-) enhancements in the `fstlib` package (the C++ core of `fst`) are addressed in `fst` and are no concern of dependent packages.

**Comment by renkun-ken** [comment]
@MarcusKlik fully agree with the separation of interfaces.

**Comment by MarcusKlik** [comment]
Hi @renkun-ken, great, yes, that way the `fst` package will be more performance-oriented and dependent packages will concentrate on usability.
