### ISSUE TITLE
Question about random row access

### ISSUE THREAD

**Issue by PeteHaitch** [fstpackage/fst#113]
Hi @MarcusKlik,

In the README you note:

> Data frames stored in the fst format have full random access, both in column and **rows** [emphasis mine]

What's the best way to achieve random row access over an _arbitrary_ set of rows, e.g. `rows = c(1:10, 50:90, 22, 21)`?  Right now, in **fstArray**, effectively what I do is to construct a series of `from` and `to` arguments from `rows` that I iteratively pass to `fst::read_fst()`. I'm wondering whether it would be possible to support something like:

```R
read_fst <- function (path, columns = NULL, from = 1, to = NULL, rows = NULL, as.data.table = FALSE, 
    old_format = FALSE) 
```

perhaps with (`from`, `to`) and `rows` being mutually exclusive.

What do you think?

Cheers,
Pete

**Comment by MarcusKlik** [comment]
Hi @PeteHaitch, thanks for your question. Indeed, the interface is not truly random at this point in the sense that you can use an arbitrary integer vector for indexing.

But that is one of the first requirements for building a `data.table` or `dplyr` interface, so that should be included in `fst` in the near future. In `fstlib` we would need to implement (C++) something similar as:

``` r
# (arbitrary) index vector
index_vec <- c(3:6, 50:48, 200:198, 600:603)
block_size <- 100

index_map <- data.table::data.table(
  Index = index_vec,
  Pos = 1:length(index_vec),
  Block = index_vec %/% block_size)

# order blocks
data.table::setkey(index_map, Block, Pos)

index_map
#>     Index Pos Block
#>  1:     3   1     0
#>  2:     4   2     0
#>  3:     5   3     0
#>  4:     6   4     0
#>  5:    50   5     0
#>  6:    49   6     0
#>  7:    48   7     0
#>  8:   199   9     1
#>  9:   198  10     1
#> 10:   200   8     2
#> 11:   600  11     6
#> 12:   601  12     6
#> 13:   602  13     6
#> 14:   603  14     6
```

So, first we order the indexes on the block number (16kB block in the `fst` format). Then we read the blocks from file in ascending order (for speed) and fill the result columns by copying the values to the correct `Pos`. Currently there is no sorting algorithm in `fstlib`, but we could define the interface and leave it to the user to implement one (using the native wrapper language for example). For `R`, the sorting with `data.table` is very fast so could be leveraged for that (eventually, `fstlib` should get it's own sorting code).

thanks!

**Comment by MarcusKlik** [comment]
Hi @PeteHaitch, your random row-access requirement is now best addressed using the '[' interface of `fst`:

``` r
library(fst)

df <- data.frame(
  X = 1:(260),
  Y = rep(LETTERS, 10),
  Z = runif(260, 4, 7),
  stringsAsFactors = FALSE
)

write_fst(df, "1.fst")

# create a reference to the fst file
x <- fst("1.fst")

# random row access identical to data.frame
testthat::expect_equal(
  x[c(1:10, 50:90, 22, 21), ],
  df[c(1:10, 50:90, 22, 21), ]
)

# display data
head(x[c(1:10, 50:90, 22, 21), ])
#>   X Y        Z
#> 1 1 A 4.453444
#> 2 2 B 4.188876
#> 3 3 C 4.416109
#> 4 4 D 5.040158
#> 5 5 E 6.689950
#> 6 6 F 4.937186
```


That off-loads the smart row selection to the `fst` package although it's not implemented in the fastest possible way yet. Currently it's still using the `from` and `to` arguments in `read_fst()` but that will be improved in the package internally in a future release!

**Comment by mikejiang** [comment]
~~Will current random row accessing cause some memory issue? Imagine a `1m x 30k` matrix stored as `fst` format, the `[c(1,1e6), ]` will cause the entire matrix to be loaded into memory all at once even though just a few rows are requested. Maybe split the read into several IO will help?~~
Never mind, I see this issue was already discussed in #143
