### ISSUE TITLE
Linux compile error v 0.8.2

### ISSUE THREAD

**Issue by mperone** [fstpackage/fst#116]
Hi Marcus,

I can't seem to get the latest version to install on Linux. I am a complete novice in compiling so this may be a very easy answer that I should be able to resolve myself. Apologies if that's the case. I've copied what I think are the relevant details below.

Best,
Matt

**Machine Info (old I know, but this is a machine I can't update):**
Red Hat Enterprise Linux Server release 6.7 (Santiago)
Kernel Version: 2.6.32-573.7.1.el6.x86_64

**R Version (old I know, but this is a machine I can't update):**
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

**GCC version:**
`
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC)
`

**I try to install with this from the R command line:**
`
install.packages(repos=NULL, lib = "[lib dir path]",  pkgs="[file path]/fst_0.8.2.tar.gz")
`

**And it runs for a while before exiting here:**
`
g++ -std=c++0x -I/[R Path]/lib64/R/include -DNDEBUG -fopenmp -I. -Ifstcore -Ifstcore_v1 -Ifstcore/LZ4 -Ifstcore/ZSTD -Ifstcore/ZSTD/common -Ifstcore/ZSTD/decompress -Ifstcore/ZSTD/compress -I/usr/local/include -I"/[Rcpp path]/Rcpp/include"   -fpic  -g -O2 -c fstcore/interface/fststore.cpp -o fstcore/interface/fststore.o
fstcore/interface/fststore.cpp: In constructor 'FstStore::FstStore(std::string)':
fstcore/interface/fststore.cpp:127: error: 'nullptr' was not declared in this scope
fstcore/interface/fststore.cpp: In member function 'void FstStore::fstRead(IFstTable&, IStringArray*, long long int, long long int, IColumnFactory*, std::vector<int, std::allocator<int> >&, IStringArray*)':
fstcore/interface/fststore.cpp:788: error: 'nullptr' was not declared in this scope
make: *** [fstcore/interface/fststore.o] Error 1
ERROR: compilation failed for package 'fst'
`

**Comment by MarcusKlik** [comment]
Hi @mperone, thanks for reporting! I've installed R version 3.1.2 and tested installing `fst` using:

```r
devtools::install_github("fstpackage/fst")
```

Everything runs as expected, the specific compiler output for `fstcore/interface/fststore.o` is:

```bash
g++ -m64 -std=c++0x -I"C:/Users/Mark/DOCUME~1/R/R-31~1.2/include" -DNDEBUG -fopenmp -I. -Ifstcore
-Ifstcore_v1 -Ifstcore/LZ4 -Ifstcore/ZSTD -Ifstcore/ZSTD/common -Ifstcore/ZSTD/decompress 
-Ifstcore/ZSTD/compress   -I"C:/Users/Mark/Documents/R/R-3.1.2/library/Rcpp/include" 
-I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 
-c fstcore/interface/fststore.cpp -o fstcore/interface/fststore.o
```

The output is practically identical to your output, but the `nullptr` exception is not thrown because my RTools installation for R 3.2.1 contains a more recent gcc compiler  (4.6).

`nullptr` is a C++11 feature that can be enabled with the `-std=c++0x` flag (as in your build). But with gcc 4.4. the C++ feature set was (apparently) not fully implemented yet, [this page](https://gcc.gnu.org/gcc-4.4/cxx0x_status.html) shows the C++ features of gcc 4.4., and the `nullptr` is not yet on it unfortunately.

For `fst` to build, you'll need GCC with at least version 4.6 or higher. So unless you can update the compiler to a newer version, I think you won't be able to build any `R` package that contains C++ code in the sources...

I'm sorry I can't be of more help to you in this regard!

greetings. Mark

**Comment by MarcusKlik** [comment]
GCC with at least version 4.6 is needed to compile `fst`, unfortunately earlier versions are missing some C++ features to compile the `fstlib` library, thanx @mperone for reporting.
