### ISSUE TITLE
Error when compressing short factor column with more than 127 levels

### ISSUE THREAD

**Issue by martinblostein** [fstpackage/fst#128]
I've stumbled upon a bug when compressing and writing short factor vectors with more than 127 factor levels. For example:

```
df <- data.frame(a = factor('X1', levels = paste0('X', 1:128)))
fst::write_fst(df, '~/test.fst')
x <- fst::read_fst('~/test.fst')
```

Attempting to coerce `x$a` to character (as when printing) yields the following error:

```
Error in as.character.factor(x) : malformed factor
```

Coercing `x$a` to integer yields `1657` on my machine (should be `1`). The same calculation with `compression < 50` yields no error. Interestingly, lengthening the vector makes the problem go away. So does decreasing the number of factor levels below 127.

**Comment by martinblostein** [comment]
A quick look at the code indicates the issue must be in line 159-191 in factor_v7.cpp. There is explicit separate cases for <128, <32768 and more factor levels. I'm not familiar enough with the compression code to immediately see the precise problem.

**Comment by MarcusKlik** [comment]
Hi @martinblostein, well spotted and thanks for reporting! Indeed, with <128 and < 32768 levels, the factor values are first compressed into 1 or 2 bytes before compressing further (that's an almost 'free' compression factor of 2 or 4 for small factors). Apparently, something strange is happening when a compression higher than 50 is used ([this code](https://github.com/fstpackage/fst/blob/develop/src/fstcore/factor/factor_v7.cpp#L178-L180) although I don't see any obvious error at the moment..)

I will investigate further, thanks again for taking the time to report the issue!

**Comment by martinblostein** [comment]
Thanks Mark, to be clear it also occurs when compression is exactly 50. Which means [this code](https://github.com/fstpackage/fst/blob/develop/src/fstcore/factor/factor_v7.cpp#L163-L165) is implicated too.

**Comment by MarcusKlik** [comment]
Hi @martinblostein, I've fixed the problem which was due to reversed parameters when calling the ZSTD compressor. The problem was only apparent because with a single row the compressed size is actually bigger than the uncompressed size.

(that also means that we should use a minimum number of rows before compression is activated, but that's another issue :-))

Thanks a lot for spotting that error, I've included your sample [in the unit tests](https://github.com/fstpackage/fst/blob/develop/tests/testthat/test_factor.R#L88-L96) if that's OK with you!
