### ISSUE TITLE
OpenMP detected, using 1 logical cores 

### ISSUE THREAD

**Issue by rexdouglass** [fstpackage/fst#137]
[Edited]

Latest development version shows 1 logical core. Can set afterward via fst::threads_fst().

I've tried multiple versions:
fst package v0.8.5 IN DEVELOPMENT built 2018-03-06 00:06:25 UTC
(OpenMP detected, using 1 logical cores)

fst package v0.8.4
(OpenMP detected, using 48 logical cores)

Checking and setting directly
fst::threads_fst()
fst::threads_fst(48L)

Can someone help me understand under what conditions multithreading kicks in?

I can get multi-threaded performance on the "Basic usage" example in the readme. I only typically see single core running on my larger real world data (both saving and loading). My data tend to be large text strings, with 100 compression. Is there some combination of compression/column types for which multicore kicks in or doesn't? Is it threaded by column or row? Etc. Thanks for any info you can provide.

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4-3 fst_0.8.4          

loaded via a namespace (and not attached):
[1] compiler_3.4.3 parallel_3.4.3 Rcpp_0.12.15

**Comment by xiaodaigh** [comment]
Try the example in the readme of

https://GitHub.com/xiaodaigh/disk.frame

It runs fst in the background on all your available workers

**Comment by rexdouglass** [comment]
Definitely running multi-threaded, thank you. I amended my original question to say I can get get the "Basic usage" to run mulithreaded as well. So my use case of lots and lots of text, with compression, seems to be the issue. I don't know enough about how FST handles mutlithreading/compression to know whether it's supposed to be multithreaded in that case or that's an edge case.

disk.frame looks awesome no matter what. Its multi-threadedness is on a single batch right, not across multiple batches?

**Comment by xiaodaigh** [comment]
Text strings? Could it be because of r string global strings pool? Which is single threaded? Perhaps you can make a mwe? 
Anyway Cognizant this is the fst thread. Yes disk.frame is multithreaded via fst and runs multiple processes via future. If you run multiple batches then each batch will follow the previous sentence.

**Comment by MarcusKlik** [comment]
Hi @rexdouglass, thanks for your question and @xiaodaigh thanks for the pointers.

I believe your question actually touches two separate issues:

1.    Can `fst` currently serialize and de-serialize `character` columns using multiple threads?
2.    How many threads are available at package start-up?

To answer the first question: version `0.8.4` of `fst` doesn't have multi-threaded `character` serialization yet. That will be available in the next (`0.8.8`) release of `fst`. All other types are multi-threaded, but not `character` columns. So, even when the package reports using 48 threads, those are not used for `character` columns yet.

The second question is about available threads within a single process. `fst` uses OpenMP for it's multi-threading and the current behavior is to select [all available logical cores](https://github.com/MarcusKlik/fst/blob/multithreaded-character/R/onAttach.R#L51-L63). But when the process is forked, for example when the `parallel` package is used to run code on a cluster, the number of threads falls back to one. That's because some issues have been reported (with the `data.table` package) with the use of OpenMP on forked processes.

So, on your system, I would expect the number of threads to be set to maximum at package start-up, are you saying that the startup message tells you that you only have a single core available?

thanks

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, indeed the global string pool that `R` uses, poses some (performance) challenges. In `R`, a new string can only be created by calling the `R` API on the main thread. That call accesses the global string pool, which slows down the creation of `character` vectors significantly, because `R` has to search the complete map of existing strings to see if it already exists. And as the string pool gets more elements, this process will be slower.

For the next version of `fst`, I will work around that by sorting the strings on multiple threads in `C++` before calling the `R` API. With less calls, creation of `character` vectors should be much faster for vectors with a smaller number of unique values. To get the mapping up to speed, we need a stacked based `hash_map` that can be run on multiple threads. A first implementation of that can be found [here](https://github.com/fstpackage/fstlib/blob/multithreaded-character/lib/interface/stack_map.cpp). [Preliminary results](https://user-images.githubusercontent.com/24658401/36874333-d3ec9466-1dab-11e8-99bb-13a749517b20.png) show that such a map can reach speeds of 150 string elements per second per core, which would be enough to enhance the speed of `character` serialization significantly!

For writing, the problem is less pronounced, because strings can be accesses on multiple threads, so `fst` can use multiple threads to serialize `character` vectors. However, because strings are scattered around main memory in `R`'s global string pool, the process of accessing that data is still comparatively slow. To solve that bottleneck, we can also use a hash map to find the unique values before accessing main memory. That idea is explained [here](https://github.com/fstpackage/fst/issues/63#issuecomment-369760857).

Your `disk.frame` package uses multiple processes to utilize the cores of a single system, so the multi-threading is of a different kind there. Basically, all cluster nodes will use a single threaded `fst` to store data, and the parallelization comes from using multiple processes. On one side that introduces overhead because of the management of the cluster, but on the other side, things can be speed up because each node can call the `R` API and run native `R` functions (each core is running a _main_ thread).

Thanks!

**Comment by rexdouglass** [comment]
Excellent discussion and explanation, thank you. I'm currently using FST to store large amounts of text (wikipedia) and have enjoyed its compression, random access, and compatibility with data.table. Multithreading for character and whatever other optimization you have planned will be much anticipated. Also, if there is a more appropriate binary format for serializing text I'd appreciate sage advice.

Updating to 8.5, I show that behavior of 1 logical core. I show all 48 when I drop back to the cran build. This is from R at the Terminal because I've read issues of Rstudio resetting the core count back to 1 under unclear conditions.

~$ R

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> devtools::install_github("fstPackage/fst", ref = "develop")
Downloading GitHub repo fstPackage/fst@develop
from URL https://api.github.com/repos/fstPackage/fst/zipball/develop
Installing fst
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/Rtmps6iCns/devtools24b36190fa0/fstpackage-fst-7cdf697'  \
  --library='/home/[user]/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘fst’ ...
** libs

[omitted] 

** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (fst)
> library(fst)
fst package v0.8.5 IN DEVELOPMENT built 2018-03-06 08:49:28 UTC
(OpenMP detected, using 1 logical cores)
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fst_0.8.5

loaded via a namespace (and not attached):
 [1] httr_1.3.1       compiler_3.4.3   R6_2.2.2         parallel_3.4.3  
 [5] tools_3.4.3      withr_2.1.1.9000 curl_3.1         Rcpp_0.12.15    
 [9] memoise_1.1.0    git2r_0.21.0     digest_0.6.14    devtools_1.13.4

**Comment by MarcusKlik** [comment]
Hi @rexdouglass, I just checked the `dev` version on a fresh Ubuntu 16 install and I can confirm your problem with the number of threads being set to 1.

The problem seems to be with the call to `parallel::detectCores()` in the package method `onAttach()`.

On Windows I get:

```
# set to 4 threads and report current setting
fst::threads_fst(4)
#> [1] 8

# verify 4 threads
fst::threads_fst()
#> [1] 4

# detect cores with the parallel package
parallel::detectCores()
#> [1] 8

# how many threads set?
fst::threads_fst()
#> [1] 4
```

The same code on Ubuntu will put the number of threads to 1 after the call to `parallel::detectCores()`, perhaps that function uses a fork that triggers a reset of the number of threads.

Thanks for reporting, I will try to fix the problem as soon as possible!

**Comment by MarcusKlik** [comment]
Hi @rexdouglass, given the problems of `fst` switching back to single-threaded mode after each fork that is triggered by `RStudio` or from within other packages, I think it's best to change the default behavior of `fst` at the end of a fork.

Currently, the number of active threads is kept at 1 after the fork ends because of possible problems with the Intel compiler reported for the `data.table` package (see e.g. [this code](https://github.com/Rdatatable/data.table/blob/master/src/openmp-utils.c#L59-L77) in `data.table`). But this precaution is reducing the user experience on Linux and only a small number of users will actually compile the package with the Intel compiler (and might not have problems even if they do so).

Also, on a `RStudio` server setup, the (remote) session is forked when a user reconnects after disconnecting from the session and that introduces unpredictable effects as well (see also #112). 

Therefore, I think it's reasonable to change the default behavior of `fst` to switch back to multi-threading after the fork ends, _unless_ the user has specifically disabled that behavior by setting `reset_after_fork = FALSE` in `threads_fst()`:

``` r
# do not restore threads after a fork
fst::threads_fst(8, FALSE)
#> [1] 8

# trigger a fork / unfork on Linux
parallel::detectCores()
#> [1] 8

# now in single threaded mode
fst::threads_fst()
#> [1] 1


# make sure threads are restored after a fork
fst::threads_fst(8, TRUE)
#> [1] 1

# trigger a fork / unfork on Linux
parallel::detectCores()
#> [1] 8

# verify 8 threads
fst::threads_fst()
#> [1] 8
```

In addition, the behavior at the end of a fork can now be set with option `fst_restore_after_fork`. Most users won't need to set that because it is expected that restoring threads after a fork won't cause any problems for them.

Hopefully this will solve your problem and offer a better experience when using `fst` with `RStudio` on Ubuntu.

It would be great if you could give the latest `dev` version a spin and see if it works for you!

**Comment by MarcusKlik** [comment]
Hi @rexdouglass, I believe we can close this issue. The `fst_restore_after_fork` option can now be used to override the default behavior of `fst` (which is that the threads are restored after the fork).

Please let me know if that doesn't work for you!
