### ISSUE TITLE
Need a way to read_fst by row index vector

### ISSUE THREAD

**Issue by renkun-ken** [fstpackage/fst#161]
The use case is as follows:

I `write_fst` a large data table of 10M+ rows and 600+ columns. Each time I need to read many small chunks in the file specified by an integer vector of row indices, e.g. `c(2000:10000, 15000:60000, 82000:250000, ...)`. Currently, there are two ways to do this:

1. Read the whole file and subset with my row index vector.
2. Read the file many times, each time a different pair of `from=` and `to=` is specified. 

The first method costs too much time especially all the rows I need is less than tenth of the data, while the second method is also too slow. 

I'm wondering if the performance can be significantly better if `read_fst` have some kind of built-in mechanism to support reading data according to a row index vector if specified.

**Comment by renkun-ken** [comment]
Just notice that `fst::fst` is able to do this. Thanks!

**Comment by MarcusKlik** [comment]
Hi @renkun-ken, thanks! Yes you can do that using `fst::fst`. At the moment the row index processing is rather rudimentary though. On subsetting, the _min_ and _max_ row index values are calculated and then normal subsetting is used to get to the result.

This is fine for row index vectors that correspond to a range of rows, but for sparse vectors, the method should be improved (also, for your example vector, data is loaded from disk that is discarded later on).

I was thinking of a method that loops over the vector and determines the chunks that require reading as well as the row index values for each chunk (a two way map). Then, after reading and decompressing the data, the elements can be put in their correct result vector position.

Such a method would not require a second `R` subsetting step, and multiple threads can be used to store the values in their correct result vector positions (although there might be cache pollution effects for random row index vectors)

Also, we could try to leverage the fact that ranges are now implemented as `ALTREP` vectors since `R 3.5.0`. If we can detect that a row vector is in fact a range, than the algorithm for determining the required chunks from the _fst_ file would be much simpler and faster.

Thanks again for your request!

**Comment by renkun-ken** [comment]
Thanks for your thought on this! I'm curious about the current mechanism of subsetting a `fst` object like the following:

```r
fst <- fst::fst("test.fst")
ids <- c(1, 3, 5, 7, 9)
fst[fst$id %in% ids, c("x1", "x2", "x3")]
```

In the code above, `test.fst` is saved from a `data.table` with a key of `id, ...`. I'm wondering if the key is used somehow?

**Comment by MarcusKlik** [comment]
Hi @renkun-ken, thanks! Yes, in that case the key could very well be used to speed up the row selection. For example, when `ids` is sorted (on the fly), the `fst` file could be read sequentially while keeping a moving pointer into the `ids` object. And the vector could be binned into chunks to know in advance which data blocks have to be read and which ones can be skipped. 

So there is a lot of possibility for speed improvements for your use case. At the moment however, `fst$id` will read the whole columns into memory and `fst$id %in% ids` will create a logical row-selection vector. 
Then. the logical vector (of length `nrow(fst)`) will be used to subset the table, so that's not very efficient yet.

In the near future, I plan to override the most important basic operators (such as `|`, `&`, `<`) for use in selection statements so that you would be able to do:

```r
fst[id < 200 & id > 10, c("x1", "x2", "x3")]
```

(which can be implemented in multi-threaded `C++`)
The `%in%` operator is more complex because it resembles a (right) join operation, where you have to iterate over 2 sets simultaneously. But for sorted sets, it can still be done on multiple threads, so these kind of operations would also be a powerful addition to `fst`'s toolkit I think.

Off course, once the row-selection is determined, we just need to keep a binary vector in memory to select the appropriate elements from the other columns, so for a large number of selected columns, the overhead of a less efficient row-selection mechanism will be smaller (but much speed in gained when selection with the binary vector is fast).

Thanks again for your questions and thoughts!
