### ISSUE TITLE
Best practice when using fst::fst

### ISSUE THREAD

**Issue by statquant** [fstpackage/fst#163]
Hello,
I discovered fst::fst recently and it looks great.
I realize it is not finished yet but was wondering hoe to use it best in current condition (v 0.8.8 from cran)
I have a 80,000,000 x 7 fst file and was surprised to witness the following:

```
R> test = fst::fst("my_file.fst")                 
R> test                                                    
<fst file>                                                 
79156180 rows, 7 columns (my_file.fst)                       
 
R> system.time({test[test$date == "2013-01-02",]})                                              
   user  system elapsed                                    
  3.027   1.904   1.806                                    
R> system.time({test[test$date == "2018-07-06",]})                                              
   user  system elapsed                                    
  3.934   1.816   2.099                                    
R> system.time({test[test$date %in% as.Date(c("2013-01-02","2018-07-06")),]})                   
   user  system elapsed                                    
 70.902   8.072  45.314 
```

Should I want to efficiently run select queries as shown above, is there a best practice to follow ?

Regards

**Comment by MarcusKlik** [comment]
Hi @statquant, thanks!

I'm also a bit puzzled by your example, because currently, the `fst` object just uses a logical vector in both of your cases. First, the complete column _date_ is read from file and after that a logical vector is calculated from the condition (e.g. `test$date == "2018-07-06"`). Then, that logical vector is used as the first argument of the `[` operator override from the `fst` package.

So any difference in speed should be caused by the second step (calculating a logical vector from a condition). If I create a similar sample set:

```r
nr_of_rows <- 1e8
ft <- data.frame(
  date = Sys.Date() + sample(1:100, nr_of_rows, replace = TRUE),
  value = sample(1:100, nr_of_rows,  replace = TRUE)
)

# write to file
fst::write_fst(ft, "my_file.fst")
```

And test with a similar filter:

``` r
test = fst::fst("~/my_file.fst")

# select some dates
some_date <- as.character(Sys.Date() + 20)
some_other_date <- as.character(Sys.Date() + 30)

# single date selection
system.time({test[test$date == some_date,]})
#> Loading required namespace: data.table
#>    user  system elapsed 
#>    2.51    1.81    1.89

system.time({test[test$date %in% as.Date(c(some_date, some_other_date)),]})
#>    user  system elapsed 
#>    5.90    2.12    5.30
```

the effects are comparable but not so extreme as in your case. With this example, the time difference is entirely caused by the relatively slow `%in%` operator:

``` r
# select some dates
column_data <- test$date
#> Loading required namespace: data.table

microbenchmark::microbenchmark(column_data == some_date, times = 10)
#> Unit: milliseconds
#>                      expr      min       lq     mean   median       uq
#>  column_data == some_date 542.0494 561.6099 608.1207 592.0558 645.4135
#>       max neval
#>  727.2793    10

microbenchmark::microbenchmark(column_data %in% as.Date(c(some_date, some_other_date)), times = 10)
#> Unit: seconds
#>                                                     expr      min       lq
#>  column_data %in% as.Date(c(some_date, some_other_date)) 3.698266 3.701825
#>      mean   median       uq      max neval
#>  3.762808 3.726666 3.793292 3.979142    10
```

There is not much you can do to speed things up in this case I think, although with such a large difference it seems that your system is hitting other boundaries (memory?).

In the future I hope to bring these type of filter operations inside the `fst` library, so that the filter can be calculated during loading on a background thread, that should increase the speed and (perhaps more important) reduce the memory footprint significantly because only selected data would  actually be loaded into memory.

Thanks for sharing your use case!

**Comment by statquant** [comment]
Thank you very much for the quick reply, I just wanted to have confirmation.
Regards

**Comment by MarcusKlik** [comment]
great, thanks for submitting!

**Comment by ghost** [comment]
Hi @statquant 
in case you are asking your frame very often you can use %fin% 
It is about 30-40% faster in this example.

```R
library(fastmatch)
some_date %fin% column_data # create index  , one time job
microbenchmark::microbenchmark(column_data %fin% as.Date(c(some_date, some_other_date)), times = 10)
Unit: seconds
                                                     expr     min      lq     mean   median       uq      max neval
 column_data %fin% as.Date(c(some_date, some_other_date)) 1.99892 2.09741 2.232911 2.226778 2.293591 2.637205    10
```
