### ISSUE TITLE
cant load fst file on v0.8.8

### ISSUE THREAD

**Issue by JaceyCJ** [fstpackage/fst#164]
Hi,

I've got two fst files but cannot load them with the version 0.8.8.
Error message:
Error in fstmetadata(full_path, old_format) : 
  Unrecognised file type, are you sure this is a fst file?

Having read through the previous issue, I know that it may need to revert back to the v0.7.3 but I cannot find the 0.7.3 tzg. Could you please provide this version or if there are alternative solutions?

Many thanks,
Jacey

**Comment by MarcusKlik** [comment]
Hi @JaceyCJ, thanks for your question!

You can still read _fst_ files created with a package version of 0.7.3 or lower by using the `old_format` parameter:

```r
ft <- fst::read_fst("my_file.fst", old_format = TRUE)
```

At some point in the future, this backwards compatability with versions before 0.7.3 will be depricated. The reason is that these files are less secure, as they don't contain hashed metadata blocks and _magic file numbers_ that can identify the file as a _fst_ file.

Hope that works for your file!

**Comment by JaceyCJ** [comment]
Hi @MarcusKlik,

Thanks for your reply. I used this parameter, but it still come up with error message:
Error in fstretrieve(fileName, columns, from, to, old_format) : 
  Unrecognised file type, are you sure this is a fst file?

Cheers,

**Comment by MarcusKlik** [comment]
Hi @JaceyCJ, that's strange, are you able to share one of the _fst_ file's for debugging? Without the actual data (or first few kB's of the data), it's hard to pinpoint the problem exactly.

Could it be that you used a `dev` version of the `fst` package to create the _fst_ file's earlier?
(backwards compatibility should work between different CRAN releases of the package, but not between releases and intermediate versions)

thanks

**Comment by JaceyCJ** [comment]
Hi @MarcusKlik ,

Here is one of the fst files. 
The share link: https://drive.google.com/open?id=1G6fuxRs8rSjxnTlk1xIzE3rsvBLO4t2u
Please Kindly check it.
I got it from a company so actually I do not know what kind of version it uses and how I can open it. Hope that you can solve out the problem.

Thanks,

**Comment by MarcusKlik** [comment]
Hi @JaceyCJ, I (finally) managed to determine what `fst` package version the company used!

Apparently, the _fst_ file was written using a `dev` version from 11 months ago. And `fst` is not backwards compatible with intermediate `dev` package builds, so that's the reason you couldn't read it.

But if you read with the correct version and then re-write using the latest `fst`, you can solve the issue:

```r

# install specific fst dev version
devtools::install_github("fstpackage/fst", ref = "784bb16")

# read 'dev' fst file's
daily_US <- fst::read.fst("daily_US_prices.fst")
monthly_world <- fst::read.fst("monthly_world_val.fst")

# write to rds format
saveRDS(daily_US, "daily_US_prices.rds")
saveRDS(monthly_world, "monthly_world_val.rds")

# restart R at this point (to avoid problems with re-installing fst)

# install the latest fst from CRAN
install.packages("fst")

# read your data file
daily_US <- readRDS("daily_US_prices.rds")
monthly_world <- readRDS("monthly_world_val.rds")

# re-write to latest fst format
fst::write_fst(daily_US, "daily_US_prices_latest.fst", compress = 100)
fst::write_fst(monthly_world, "monthly_world_val_latest.fst", compress = 100)
```

that should update your data file to the latest version! I used maximum compression as the company did in the source files.

This issue really got me thinking whether it would be better if `fst` included a unique build number for each commit. That way, any _fst_ file could be traced back to the precise package commit version.

Thanks, I hope the code enables you to continue working on your data!

**Comment by MarcusKlik** [comment]
On the topic of providing the build version:

* the `data.table` package signs it's builds on `Travis` but does not add a unique marker in the code repository for each build. So users that installed the package from `Travis` can retrace the build but when the package was installed from source, the specific build information is lost.
* Another possibility would be to add a target to the `Makevars` file in `src` that generates some extra lines in the `C++` source code. Those lines would define a version which could make it's way to a (hidden) function `fst:::build_version()`.

**Comment by JaceyCJ** [comment]
Hi @MarcusKlik, thanks for your help. I finally installed the fst version with my Windows (not the Mac as it comes up with the clang error:
clang: error: unsupported option '-fopenmp'
make: *** [FastStore.o] Error 1
ERROR: compilation failed for package ‘fst’)
and opened the files.
You really give me a great hand.
By the way, the OSX is complicated to install the version.

Thanks again.

**Comment by MarcusKlik** [comment]
Hi @JaceyCJ, you're welcome!

The Mac error is due to missing `OpenMP` support for your installed version of the `Clang` compiler. But with some extra steps, you can get `OpenMP` to work correctly on `OSX` (`OpenMP` is used for multi-threading).

If you're interested, you can take a look at [this page](https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac) from the `data.table` repository. The procedure described there will probably solve the errors you get on your Mac and allow you to compile the `dev` version without problems.

Thanks!
