### ISSUE TITLE
rds file size is smaller

### ISSUE THREAD

**Issue by alperyilmaz** [fstpackage/fst#168]
Hi,
I was testing the data frame shared in main page:

```R
nr_of_rows <- 1e7

df <- data.frame(
    Logical = sample(c(TRUE, FALSE, NA), prob = c(0.85, 0.1, 0.05), nr_of_rows, replace = TRUE),
    Integer = sample(1L:100L, nr_of_rows, replace = TRUE),
    Real = sample(sample(1:10000, 20) / 100, nr_of_rows, replace = TRUE),
    Factor = as.factor(sample(labels(UScitiesD), nr_of_rows, replace = TRUE))
  )
```

Then I save the data frame as fst (default options), fst (with max compression) and rds. Here's code for saving files

```R
library(fst)
write.fst(df, "dataset.fst")   # write_fst() yields same filesize
write.fst(df, "dataset_compressed100.fst", 100)
saveRDS(df, "dataset.rds")
```

And here's the file sizes:

```bash
$ ls -alh dataset*.fst dataset.rds
-rw-r--r-- 1 alper alper 25M Sep  4 11:54 dataset_compressed100.fst
-rw-r--r-- 1 alper alper 59M Sep  4 11:54 dataset.fst
-rw-r--r-- 1 alper alper 30M Sep  4 11:53 dataset.rds
```

The benchmarks of the `fst` package showed rds file size as 1000 MB and 303 MB for the same data frame used in benchmarking. My system's CPU is `Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz` and I'm writing to SSD (make and model: `KINGSTON SHFS37A`).

Maximum compressed fst is barely smaller than rds file and default compressed fst file is twice as large than rds counterpart :disappointed:   
Is it possible that configuration of my system effects the compression? Do I need to install additional packages or change some settings?

**Comment by renkun-ken** [comment]
The comparison is a bit unfair since `saveRDS` uses `compress = TRUE` by default. You may try `saveRDS(df, "dataset_uncompressed.rds", compress = FALSE)` to compare with uncompressed fst.

**Comment by MarcusKlik** [comment]
Hi @alperyilmaz, thanks for sharing your benchmarks!

With `saveRDS()`, the user can select several compression algorithms, each with very different performance characteristics: `gzip`, `xy` and `bzip2`. The default compression algorithm used by `saveRDS()` is `gzip`.

The `fst` packages uses the `LZ4` and `ZSTD` compression algorithms for high-speed and medium speed compression. These compressors both have the advantage of very high speed decompression (regardless of the compression setting). This nicely aligns with the goals of the `fst` package.

The downside of using `LZ4` and `ZSTD` is that in cases where the highest possible compression is needed, these compressors will fall short compared to extreme compressors such as `xy`. However, for `fst` the cost (in time) of these compressors is too high. Using your dataset:

``` r
nr_of_rows <- 1e7

df <- data.frame(
  Logical = sample(c(TRUE, FALSE, NA), prob = c(0.85, 0.1, 0.05), nr_of_rows, replace = TRUE),
  Integer = sample(1L:100L, nr_of_rows, replace = TRUE),
  Real = sample(sample(1:10000, 20) / 100, nr_of_rows, replace = TRUE),
  Factor = as.factor(sample(labels(UScitiesD), nr_of_rows, replace = TRUE))
)


write_bench <- microbenchmark::microbenchmark(
  saveRDS(df, "dataset_gzip.rds", compress = "gzip"),
  saveRDS(df, "dataset_bzip2.rds", compress = "bzip2"),
  saveRDS(df, "dataset_xz.rds", compress = "xz"),
  fst::write_fst(df, "dataset.fst"),
  fst::write_fst(df, "dataset_compressed100.fst", 100),
  times = 1
)

data.table::data.table(
  Expr = write_bench$expr,
  Speed = 1e3 * object.size(df) / write_bench$time
)

#>                                                    Expr       Speed
#> 1: fst::write_fst(df, "dataset_compressed100.fst", 100)  138.902818
#> 2:       saveRDS(df, "dataset_xz.rds", compress = "xz")    1.301675
#> 3:   saveRDS(df, "dataset_gzip.rds", compress = "gzip")   14.521779
#> 4:                    fst::write_fst(df, "dataset.fst") 3472.871449
#> 5: saveRDS(df, "dataset_bzip2.rds", compress = "bzip2")    6.700827
```

These results show that `fst` at a setting of `compress = 50` (the default) is a factor of ~2500 times faster than `xy` on my system. So `xy`, although extremely good at reaching very high compression ratio's, is completely impractical for use by `fst`.

So in general it's very hard to say what the best compressor is, it all depends on the use case you have. If you have a disk with a maximum speed of a few MB/s (e.g. a USB drive), `xy` is your best choice. For higher disk speeds other algorithms are probably more useful.

It could be nice however to add a slower compressor with a higher compression ratio to `fst`. Because `fst` is multi-threaded, the speeds for algorithms like `gzip` will increase with the number of cores used and practical speeds might be reachable, something to consider as a future expansion perhaps!

thanks!

**Comment by alperyilmaz** [comment]
Hi @MarcusKlik  and @renkun-ken ,
Thanks for detailed explanations. I thought the benchmarks were for default options for both `saveRDS()` and `write.fst()`.. Now it's more clear.. It's good to know pros and cons of different compressors..

**Comment by MarcusKlik** [comment]
You're welcome @alperyilmaz!

It's definitely interesting to take a look at other compressors for future expansions of `fst`, for example to provide a `compress = "ultra"` mode. Such a mode could be used to facilitate highly compressed _fst_ files on slow (network) drives or USB sticks.

Also, `ZSTD` provides a dictionary compression option, where training data can be used to compile a dictionary that will speed up the algorithm on later runs. Using a dictionary will also improve the compression ratio significantly (see [here](https://github.com/facebook/zstd#the-case-for-small-data-compression)).

(However, the thing with dictionary compression is that you can't really determine a suitable dataset for training because the type of contents of a column are unknown a-priori :-))

thanks!
