### ISSUE TITLE
Should I zip fst or add more compression factor?

### ISSUE THREAD

**Issue by hope-data-science** [fstpackage/fst#229]
fst is amazing for its speed and compression of data.frame in R. When I use default setting to write fst, I still want to make the file size smaller. Should I just use zip formate to compress it, or should I just increase the compression factor using parameter `compress`? Which is faster? Which is smaller? Any trade-off benchmark for speed and size?

Thank you.

**Comment by MarcusKlik** [comment]
Hi @hope-data-science ,

thanks for submitting your question and using `fst`!

Yes, using the build in compressor is much faster than zipping the _fst_ file after it has been written to disk. The reason is that `fst` compresses the data on background threads while writing to disk, so your cores are put to better use :-)

Also, `fst` has optimized compression for different column types, for example `integer` compression follows a different strategy than `logical` compression. Knowing the type in advance helps a lot for compression. By zipping the file at a later moment, you will lose this advantage.

And last but not least, compressed _fst_ files still provide random access, this feature is not available for zipped files.

Are _fst_ files created with maximum compression settings small enough for your use case?

thanks and best!

**Comment by hope-data-science** [comment]
Excellent, I try to use package `zip` and I find that I got an even larger file. `fst` is amazing because I never need the whole piece for any task. 

A small thing is, as we usually use `fst` for big data, set the `as.data.table = TRUE` might help, or the computer would break every time by default.

Another question is, why not set the default `compress = 100` as it seems faster and the file is smaller. Any drawback to set a high compress factor? Thanks.

**Comment by MarcusKlik** [comment]
Hi, that's an interesting question!

If your goal is to produce the smallest _fst_ files possible, than using maximum compression is the correct choice. More so because the reading speed will not suffer too much from high compression factors. That's because the compressors that `fst` uses (`ZSTD` and `LZ4`) still provide high decompression speeds at high compression settings).

If your goal is to write (and read) _fst_ files as speedy as possible, than the answer is more complicated. The speed will depend on the effective speed of the (SSD) drive that's used for reading and writing.

* If the drive speed is infinite, using zero compression would be the best option. Files would be larger, but write and read times would be the shortest.
* If the drive speed is very low, than using a high compression is better. The smaller file sizes will make shorter write and read times (minimizing the IO bottleneck at the expense of CPU resources).

Your drive will probably be in between these two extremes, so there is an optimal compression ratio for your setup.

The default compression setting optimizes for a reasonably fast SSD drive. If you use a slower (network) drive, chances are you will benefit a lot from increasing the compression ratio :-).

Hope this helps you!

**Comment by hope-data-science** [comment]
Thank you for the detailed answer which is amazing.

This is a little contrary to common sense. I am currenly trying to figure out a best solution for myself (maybe applicable to many like me) : space is cheaper than time (time is life), writing time is cheaper than reading time (we read more than we write the file). Nevertheless, the device SSD is an uncontrollable factor that we have little idea of. The file (.fst) might be read on any computer (the hardware is better or worse, we have no idea). What is the best compress factor according to the circumtances stated above (shortest reading time)? According to your explanation, it seems that set the compress factor to 0 could yield the best performance for shortest reading time.

One more thing to consider is that, we need to transfer such file often, a large file size might increase the time of file transfer between devices, which is undesirable. This is all about time. Ha ha!

Still no idea to make it best, maybe another benchmark should be made. But one thing is for sure, `fst` is the best solution for such circumstances. Thank you for your contribution!

**Comment by MarcusKlik** [comment]
Hi @hope-data-science , you're right, there are even more parameters to take into account :-)

Yeah, if you have to transport the file and read files much more often than you write them, than high compression is probably what you're looking for!

thanx and best
