### ISSUE TITLE
Feature request: Support for bit64

### ISSUE THREAD

**Issue by HughParsonage** [fstpackage/fst#28]
For example: https://stackoverflow.com/questions/42379995/bit64-integers-with-fst 

```r
library(bit64)
library(data.table)
library(fst)
library(magrittr)

# Prepare example csvs
DT64_orig <- data.table(x = (c(2345612345679, 1234567890, 8714567890)))
fwrite(DT64_orig, "DT64_orig.csv")

# Read and move to fst
DT64 <- fread("DT64_orig.csv")
write.fst(DT64, "DT64_fst.fst")

DT_fst2 <- 
  read.fst("DT64_fst.fst") %>%
  setDT

# bit64 integers not preserved:
identical(DT_fst2, DT64)
```

**Comment by MarcusKlik** [comment]
Thanks for the issue report @HughParsonage. Indeed, column attributes are not implemented at the moment, but is on top of the feature list for the next version of `fst`. Serialization of attributes is also required for supporting `Date` and `POSIXt` classes for example. This issue is also related to issue #17 and issue #22.

**Comment by MarcusKlik** [comment]
Hi @HughParsonage, the `integer64` type (from the `bit64` package) has now been implemented (on branch develop). A [unit test](https://github.com/fstpackage/fst/blob/develop/tests/testthat/test.integer64.R#L19-L32) was added with code comparable to your example.

Thanks again for reporting the issue!
