### ISSUE TITLE
When column in "Date" format is written and later read, it comes back as an integer!

### ISSUE THREAD

**Issue by dan-reznik** [fstpackage/fst#33]
write.fst(fname,df) # imagine df$date is Date
df <- read.fst(fname) # df$date comes back as "int"

**Comment by MarcusKlik** [comment]
Hi @carioca67 , currently attributes of columns are not serialized. That will be fixed in the next version of the `fst` package, after which also `POSIXct` classes and other classes which have special attributes (such as `bit64`) will be supported. This problem was also reported in issue #22. Thanks for reporting!

**Comment by MarcusKlik** [comment]
Duplicate of issue #22. Next package version will have a fix.

**Comment by MarcusKlik** [comment]
Hi @carioca67, this issue is fixed on the development branch. the `Date` type should now be respected. I'm converting `Date` types which have a `double` type as base to `integer` internally as can be seen in [this test](https://github.com/fstpackage/fst/blob/develop/tests/testthat/test.date.R#L15-L19). The `Date` type based on `integers` gives a much better performance and higher compression ratio's than the type based on `double's`.

Thanks again for reporting!

**Comment by dan-reznik** [comment]
Wow Mark, that's fantastic. You should publish this to r-bloggers.com

**Comment by MarcusKlik** [comment]
Thanks! And I guess I will as soon as the next CRAN version of `fst` is out :+1: 
The same holds for the OpenMP multi-threading support that `fst` now has. That boosts the performance significantly and I think it would be nice to compare benchmarks of several systems (e.q. `feather`, `saveRDS/readRDS`, `data.table's` multi-threaded `fread/write` (also using OpenMP) and perhaps `MonetDBLite` (see for example #62) .

Thanks again for reporting the issue!
