### ISSUE TITLE
Restore data.table class on read

### ISSUE THREAD

**Issue by nextpagesoft** [fstpackage/fst#57]
First of all - fantastic job! One thing I noticed is that object read from disk is initialized to class 'data.frame' even though it was 'data.table' at save. Can it be automatically restored in 'write.fst' automatically or the full class is not serialized and is assumed to be 'data.frame'?

**Comment by MarcusKlik** [comment]
Hi @nextpagesoft , thanks for your request! It's somewhat related to issue #12 , where support for `tibble`'s is requested.

From a design point of view, the core code for the `fst` package will be available in the near future as a separate C++ library. At that point, it will be relatively straightforward to implement a version of `fst` in other languages (e.g. Python). The `tibble`, `data.table` and `data.frame` classes are specific R constructs, and therefore they can't really have specific meaning in the upcoming C++ core library. However, because they are basically different interfaces to the same underlying data-structure, it won't hurt to 'remember' the interface of the data-set that was used to store the data, so that the class is automatically restored, as per your request.

When a specific `fst` file, created with R, is read from another language (say Python), that class attribute won't have any special meaning, so the default can be used at that point.

Thanks again, the class attribute will be serialized in the next release!

**Comment by MarcusKlik** [comment]
Hi @nextpagesoft, thanks again for requesting this feature. However, because `fst` is now a pure `C++` library at it's core, the specific type of `R` table ( `data.table`, `tibble` or `data.frame`) has no meaning in the `fst` format. It's a bit like a `csv` file where there is also no information on the type of table that was used to store it initially.

In method `read_fst` there is a parameter  `as.data.table` that can be used to return the table in that format. This is needed because when a sorted `data.table` is serialized, `fst` also serializes the keys. When `as.data.table` is set to `TRUE`, these keys [are restored](https://github.com/fstpackage/fst/blob/develop/R/fst.R#L189-L198).

For unsorted tables, it would be just as fast to use:

``` r
dt <- data.table(X = 1:10)
write_fst(dt, "1.fst")

dt_read <- as.data.table(read_fst("1.fst"))  # almost no overhead
```

the cast to a `data.table` is very efficient and has almost no overhead because the columnar data isn't actually copied (see also #12).

I hope this will work for you!

**Comment by DanielLewandowskiAtradius** [comment]
Hi @MarcusKlik, I've been using this solution for a long time to be honest and I would simply drop this request altogether. I just wrote a wrapper and am happy with it:
```R
loadFST <- function(file, as.data.table = TRUE, ...) {
  fst::read.fst(path = file, as.data.table = as.data.table, ...)
}
```

BTW, I thought that one can always do `dt <- setDT(read_fst("1.fst"))` regardless of `dt` being sorted or not. According to `data.table` help file itself `as.data.table` does make a copy, whether `setDT` is a "by reference" operation.

**Comment by nextpagesoft** [comment]
Hi @MarcusKlik, thanks for the pointers. I've been using this solution for a long time to be honest and I would simply drop this request altogether. I just wrote a wrapper and am happy with it:
```R
loadFST <- function(file, as.data.table = TRUE, ...) {
  fst::read.fst(path = file, as.data.table = as.data.table, ...)
}
```

BTW, I think one can always do `dt <- setDT(read_fst("1.fst"))` regardless of `dt` being sorted or not. According to `data.table` help file itself `as.data.table` does make a copy, whether `setDT` is a "by reference" operation.

**Comment by MarcusKlik** [comment]
Hi @nextpagesoft, thanks for that! And yes, you're right, you can always use `setDT`. The only thing is that the key (if any) will be lost:

``` r
library(data.table)
library(fst)

dt <- data.table(X = 1:100, Y = 100:1)
setkey(dt, Y)
key(dt)
#> [1] "Y"

write_fst(dt, "1.fst")
dt <- setDT(read_fst("1.fst")) 

key(dt)
#> NULL
```

That's because the `data.frame` that is returned (the default return type) can't hold a key. If you use 'as.data.table = TRUE`, the key [gets set](https://github.com/fstpackage/fst/blob/develop/R/fst.R#L189-L198) without actually re-sorting the table (the _sorted_ attribute is just added to the table).

You can also sort the table again after reading but using 'as.data.table = TRUE` will be faster for tables that were sorted when writing. The sort operation is relatively expensive:

``` r
library(data.table)
library(fst)

dt <- data.table(X = 1:100000000)  # 400 MB

res <- microbenchmark::microbenchmark(
  setkey(dt, X),
  times = 10
)

# sorting speed in GB/s
as.numeric(object.size(dt)) / median(res$time)
#> [1] 1.046598
```

In this case the sorting speed is actually lower than the read operation itself :-)

Thanks for commenting, I will close the issue then!
