### ISSUE TITLE
Error std::bad_array_new_length when reading.

### ISSUE THREAD

**Issue by juanpide** [fstpackage/fst#59]
I've created a simple toy data.table with 

```
temp <- data.table(A=1:10,B=10:1)
write.fst(temp,"temp.fst", 90)
```
Moved the file temp.fst to a second computer and tried to read it with

```
 my3  <- read.fst("temp.fst", as.data.table = T)
```
But I get this error:
```
Error in eval(substitute(expr), envir, enclos) : 
  std::bad_array_new_length
```

What does it mean?
How can I solve it?
I've tried reinstalling fst from github but the problem is still there.

If I try to create it on the second computer and read it in the same computer I don't have any problem.
Both fst packages are version 0.7.2

**Comment by MarcusKlik** [comment]
Hi @skanskan , thanks for reporting the issue. Could you specify the operating systems and OS of the two computers? Currently, the only [restriction](https://github.com/fstpackage/fst/blob/develop/DESCRIPTION#L13) that I have imposed on the package is that the system should have a 'little endian' type of processor (eventually, `fst` will need a (fast) little- to big- converter and vice-versa).

If both systems have identical endianness, `fst` files should be read correctly after moving the file, so any additional information on this error would be very welcome!

**Comment by juanpide** [comment]
One is Windows 7 x64, i7 4790K .
the other one is Windows 10 x64, i7 930.
Do you want me to do any special test?

**Comment by MarcusKlik** [comment]
Thanks for that! Both 64-bits Windows, very strange indeed. If possible, it would be great if you could generate two `fst` files. One from your Windows 7 machine (e.g. _win7.fst_) and one from your Windows 10 machine (e.g. _win10.fst_), both using your toy example code. If you could sent those files to [me](https://github.com/fstpackage/fst/blob/develop/DESCRIPTION#L7), I can compare them (at the byte level) to see what the difference is and which part of the `fst` code is responsible for that.

(and I can do the same as soon as I have access to a Windows 7 machine)

Much obliged!

**Comment by juanpide** [comment]
How can I know the exact subversion and build date installed?

In the meantime I've created 4 files with the same toy example.
temp0Win10.fst    Windows 10, zero compression.
temp0win7.fst       Windows 7, zero compression.
tempxwin7.fst       Windows 7, compression 90.
tempxWin10.fst     Windows 7, zero  compression.



Two in the win10 computer, two in the win7.


[example.zip](https://github.com/fstpackage/fst/files/985037/example.zip)

Maybe is not a bug but a problem with my installation.

Regards

**Comment by MarcusKlik** [comment]
Thanks for investing the time to tackle this issue! Looking at the `fst` files in your zip (didn't know that you could paste a zip into an issue, nice to know), I can see that both files were generated by a dev version of `fst`, but with different build numbers. Although `fst` files generated with 'CRAN releases'  are backwards compatible, files generated with different versions of the dev install are not (at this point). I think your re-install with the CRAN version might have failed, perhaps because the dev version was still loaded.

If possible, could you try deleting the current installations of the package and then reinstall from CRAN on both computers? That should work. You can also install the same dev version on both computers, running:

```r
devtools::install_github("fstpackage/fst", ref = "develop")
```

(the dev version is currently on a separate branch in the repository but that will change after the next official release)

Hopefully that will solve your migration problem. It might be an idea to add an extra marker to the format with the exact build number. That way, `fst` can generate an error or warning if different dev versions are used for reading and writing.

**Comment by juanpide** [comment]
Thank you.
I suspected it was something related with version missmatch.
I'll try it.  
I didn't know it would change so much.

At this moment What features will I miss if I use the cran version instead of the dev one?

**Comment by MarcusKlik** [comment]
Apart from bug-fixes, in the dev version the file format is updated to accommodate dynamically adding rows or columns to an existing `fst` file as well as custom column attributes. But the R interface to that functionality is not finished yet, so you won't profit from that at this point. Also, the compressors are updated to newer versions so there might be a (small) performance increase in the dev version.

**Comment by MarcusKlik** [comment]
Hi @skanskan , for development versions, the build number is now shown when `fst` is loaded:

```r
> library(fst)
fst 0.7.3 IN DEVELOPMENT built 2017-06-13 03:27:54 UTC
(OpenMP detected, using 4 cores)
```

From `fst` version 0.8.0 onward (next CRAN release), the package is kept backwards compatible with `fst` files that were created with previous releases, which should also hold for development releases.

I'm closing this issue for now, please let me know if you have any additional problems and thanks again for reporting.

**Comment by juanpide** [comment]
That's great.  Thank you very much.
