### ISSUE TITLE
Multi threading phase 1: parallel inner loops for integer, logical and double read/write 

### ISSUE THREAD

**Issue by fstpackage** [fstpackage/fst#62]
The `fst` package implements serialization of integer, double and logical columns with a common (inner) loop. This loop can be parallelized relatively easily using OpenMP. Serialization of column blocks (writes) should be performed in order (with a 'pragma omp ordered' section).  Compression and decompression can be performed out-of-order and in parallel. Note that R vectors can only be created from C++ using the master thread ('pragma omp master').

**Comment by MarcusKlik** [comment]
Phase 1 is now complete. Compressed reads and writes of integer, double, logical and factor columns are implemented using OpenMP multithreading. Benchmarks look very promising on this initial version!

![image](https://user-images.githubusercontent.com/24658401/27053854-27608f8c-4fbf-11e7-9eea-5c31d95bee7e.png)

The benchmark shown was generated on a  4-core laptop @2.5GHz with a Samsung EVO 850 SSD drive using the following script:

https://gist.github.com/MarcusKlik/ae0549ad30f3d434d9fa06d62abd5180

**Comment by MarcusKlik** [comment]
A few observations on the benchmark above:

* The benchmark was generated using a random dataset that was re-created before each measurement ensuring that the SSD can't use caching.
* The dataset used:

```r
  nrOfRows <- 20000000

 dt <-  data.table(
    Integer = sample(1:1000, nrOfRows, replace = TRUE),
    Double = sample(1:1000, nrOfRows, replace = TRUE) / 100.0,
    Logical = sample(c(TRUE, FALSE), nrOfRows, replace = TRUE),
    Factor = factor(sample(state.name, nrOfRows, replace = TRUE)))
```
* On this system, reading a `fst` file is disk bound. Increasing parallelism hardly increases the read speed. Increasing compression on the other hand, increases the read speed from ~950 MB/s (zero compression) to more than 2 GB/s due to smaller resulting files (again showing the system is disk-bound).
* Writing a `fst` file is CPU bound. Because compression speed is much lower than decompression speed for the algorithms used (LZ4 and ZSTD), writing really benefits from added parallelism. Write speed for the dataset using all columns (the 'All' row of figures) peaks at more than 3 GB/s at 3 cores and a compression setting of 20. On systems with more cores, higher compression settings increases this speed further (and the peak shifts to the right)..
* Using more than 4 cores (there are 8 logical cores using hyper-threading) only increases performance marginally on this 4/8 core laptop. That's because hyper-threading doesn't really add to the computational power of the system.
* The thread scheduling mechanism is not optimized at this point. The current implementation used OpenMP to create parallel inner loops (see [this code](https://github.com/fstpackage/fst/blob/develop/src/fstcore/blockstreamer/blockstreamer_v2.cpp#L209-L270) for example). With smarter scheduling a lot of additional performance can be gained. With (multi-threaded) timers a clearer picture can be obtained of the slowest parts of the code.

**Comment by MarcusKlik** [comment]
Closing this issue, further speed improvements may be expected when the character-type columns are implemented with multiple threads and the thread scheduling is investigated with accurate timers. Directly using the counters from `microbenchmark`'s c code is probably the easiest solution for that.
