### ISSUE TITLE
Look great.  But better y-axis please.

### ISSUE THREAD

**Issue by mattdowle** [fstpackage/fst#7]
Just saw your new package.  Looks very nice!  Thanks for the praise on `fwrite`.

I'm finding the headline chart hard to grasp, though.  For example, what does "0" for `fread` mean compared to a speed of 3,000 for `fst`?  Is this a test on 1e7 rows and what are the actual timings?  Here's the chart and below it my suggestion : 

![image](https://cloud.githubusercontent.com/assets/2779998/22047103/c69fe7ae-dcd9-11e6-9588-35eadf2a894a.png)

I'd much prefer to see a size chosen and then the amount of time reported, like I did in [this article](http://blog.h2o.ai/2016/04/fast-csv-writing-for-r/) : 

![image](https://cloud.githubusercontent.com/assets/2779998/22047275/e5b3d366-dcda-11e6-8300-6a4523518880.png)

Where does `fst` fit into that table for example?

**Comment by fstpackage** [comment]
Thanks a lot! I've added a table to the README showing the actual benchmark numbers and upgraded some of the axis titles. A note on the benchmark:

As you can see, I'm using factors in the data frame and not character vectors. This could work in the advantage of the binary writers (feather, fst and saveRDS), because they can (potentially) save the integer factor data instead of using the actual string data. On the other hand, the strings are short, so the difference in length is not large.

**Comment by fstpackage** [comment]
Closing issue, graphs and table were updated in fst package and on fstpackage.github.io

**Comment by mattdowle** [comment]
Great - yes the table conveys nicely now.  Thanks for doing so quickly!  Could I make final small ask that a column is added to the table as well showing "csv" next to fread and fwrite,  and "bin" for the others please.

**Comment by MarcusKlik** [comment]
Thanks, I've added a format column like you did in your article for better comparison and will add the performance as measured on a mid-range laptop soon.
