### ISSUE TITLE
POSIXct class lost

### ISSUE THREAD

**Issue by statquant** [fstpackage/fst#73]
Hello, I am using the dev version of `fst`, if I can see that `Date` attribute is kept, it looks liks `POSIXct` are lost when a fst file is red back.
Am I missing something ?
Thanks

**Comment by MarcusKlik** [comment]
Hi @statquant, thanks for submitting your issue! Indeed, the dev version of `fst` is now supporting `Date` classes, but the `POSIXct` type is still due. Because `doubles` (the `POSIXct` underlying type) values are much harder to compress than `integers`, the most logical choice for the `Date-Time` type in the `fst` core library (C++) is a 64-bit integer value representing the number of nanoseconds since the beginning of 1970 (in the UTC time zone). That requires a conversion between doubles and 64-bit integers and takes some more work to do in parallel (using OpenMP).

This `Date-Time` accuracy is identical to the accuracy used in @eddelbuettel's [`nanotime`](https://github.com/eddelbuettel/nanotime) package (1e-9 seconds), so the `fst` package can support both classes using the same underlying serialization type.

From an R users point of view, it would be very convenient to have all class attributes just serialized in the `fst` format. However, the core of `fst` is now completely rewritten to C++ without any dependencies on R libraries. That way, `fst` can easily be implemented in Python or any other language (it just needs a (relatively small) wrapper around the C++ core library). But many `R` classes have no meaning in other languages, so for each class attribute we have to use an underlying type that is defined uniformly across languages. For the `Date-Time` class, the `nanotime` definition seems very appropriate and portable.

So you're not missing anything but the `fst` package is at the moment. However, that will be corrected with the next release (in a couple of weeks).

thanks again!

**Comment by MarcusKlik** [comment]
But if you want, you can set the class attribute manually as shown in the example below::

```r
library(fst)

# Sample data
dt <- data.frame(DateTime = Sys.time() - 1:5)
print(dt)
#>              DateTime
#> 1 2017-07-29 00:28:22
#> 2 2017-07-29 00:28:21
#> 3 2017-07-29 00:28:20
#> 4 2017-07-29 00:28:19
#> 5 2017-07-29 00:28:18

# Column class is POSIXct
print(class(dt$DateTime))
#> [1] "POSIXct" "POSIXt"

# write / read cycle
fstwrite(dt, "dt.fst")
dt_read <- fstread("dt.fst")

# Class not preserved
print(class(dt_read$DateTime))
#> [1] "numeric"

# Set class manually
class(dt_read$DateTime) <- "POSIXct"

# Class is now correctly set
print(class(dt_read$DateTime))
#> [1] "POSIXct"

# Table is equal to the original
print(dt_read)
#>              DateTime
#> 1 2017-07-29 00:28:22
#> 2 2017-07-29 00:28:21
#> 3 2017-07-29 00:28:20
#> 4 2017-07-29 00:28:19
#> 5 2017-07-29 00:28:18
```

Hope this helps until the next `fst` release!

**Comment by statquant** [comment]
Thanks but OC I do not know the name of the column in advance ;).
But got you point, thank you I think fst might become THE read/write package of R

**Comment by MarcusKlik** [comment]
Hi, thanks a lot and very good point, when reading a unknown data set, you don't know the type in advance off course :-)

Perhaps when `fst` supports also serialization of non-tabular data (and the `list` column type), it might become a good substitute for `saveRDS` / `readRDS` (but with random access for lists and vectors). A powerful difference with those internal functions is that with `fst` the data can be compressed and written to disk with multiple threads (OpenMP), so it will be much faster 👍 (also because of the `LZ4` and `ZSTD` compressors).

Will keep you posted on the progress of this issue!

**Comment by eddelbuettel** [comment]
>  For the `Date-Time` class, the `nanotime` definition seems very appropriate and portable.

And as i recall, that use of "nanoseconds since epoch" is also "generic" and used by other languages (which was part of my motivation of adding it to R), just how "(fractional) seconds since epoch" used by `POSIXct` is common across languages and systems.

Looking forward to a new `fst` too.  Keeping the core independent and portable is a very good approach.

**Comment by MarcusKlik** [comment]
Hi @eddelbuettel, thanks for that, so indeed both types of representations should be supported by `fst`, also within the C++ core library. Converting to `int64` might still be preferable from a performance point of view (compression with bit packing is very efficient for `int64`'s for example)

Perhaps of interest to you is that I'm planning to introduce `SIMD` to `fst` after the next release. Converting from `double` to `int64` (and vice versa) can be done very efficiently using `SIMD` instructions and implementing this conversion might be a good starter for `SIMD` use in `fst`. As the `SIMD` backend I'm thinking of using [Blaze](https://github.com/ChingChuan-Chen/RcppBlaze/blob/master/src/RcppBlaze.cpp) (very familiar to you obviously) or Agner's  [vectorclass library](http://www.agner.org/optimize/vectorclass.pdf).

It's a challenge though, because I need to compile multiple versions of the `SIMD` library with different `SIMD` compiler options (e.g. `SSE4`, `AVX`, `AVX2` and perhaps the `AVX512` extensions now supported by the new Intel processor lineup). A run-time dispatcher will choose the correct library depending on the capabilities of the user system and the maximum available `SIMD` instruction set will be determined when the package is loaded. I don't believe that is done before with an R package so will be very interesting to get working :-)

Anyway, thanks again for the information and I will let you know when the `nanotime` class is fully supported by `fst`  !

**Comment by MarcusKlik** [comment]
Hi @eddelbuettel and @statquant. The `POSIXct` and `nanotime` types are now implemented in `fst` (dev version):

``` r
# nanotime, integer64 and POSIXct column types
dt <- data.frame(
  Nano = nanotime::nanotime(Sys.time()) + 1:5,
  POSIXct = as.POSIXct(Sys.time()))
attr(dt$POSIXct, "tzone") <- "Pacific/Tahiti"  # wishful thinking

# show formatting
print(dt)
#>                                  Nano             POSIXct
#> 1 2017-09-13T12:22:43.561173001+00:00 2017-09-13 02:22:43
#> 2 2017-09-13T12:22:43.561173002+00:00 2017-09-13 02:22:43
#> 3 2017-09-13T12:22:43.561173003+00:00 2017-09-13 02:22:43
#> 4 2017-09-13T12:22:43.561173004+00:00 2017-09-13 02:22:43
#> 5 2017-09-13T12:22:43.561173005+00:00 2017-09-13 02:22:43

# timezone is set
attributes(dt$POSIXct)
#> $class
#> [1] "POSIXct" "POSIXt" 
#> 
#> $tzone
#> [1] "Pacific/Tahiti"

# write to fst file
fst::fstwrite(dt, "1.fst")

# types visible in metadata
fst::fstmeta("1.fst")
#> <fst file>
#> 5 rows, 2 columns (1.fst)
#> 
#> * 'Nano'   : nanotime
#> * 'POSIXct': POSIXct

# nanotime, integer64 and POSIXct types retained
dt_read <- fst::fstread("1.fst")
print(dt_read)
#>                                  Nano             POSIXct
#> 1 2017-09-13T12:22:43.561173001+00:00 2017-09-13 02:22:43
#> 2 2017-09-13T12:22:43.561173002+00:00 2017-09-13 02:22:43
#> 3 2017-09-13T12:22:43.561173003+00:00 2017-09-13 02:22:43
#> 4 2017-09-13T12:22:43.561173004+00:00 2017-09-13 02:22:43
#> 5 2017-09-13T12:22:43.561173005+00:00 2017-09-13 02:22:43

# types come back correctly
identical(dt$Nano, dt_read$Nano)
#> [1] TRUE
identical(dt$POSIXct, dt_read$POSIXct)
#> [1] TRUE

# nanotime is returned as a integer64 S3 and nanotime class
attributes(dt_read$Nano)
#> $.S3Class
#> [1] "integer64"
#> 
#> $class
#> [1] "nanotime"
#> attr(,"package")
#> [1] "nanotime"

# POSIXct column has the correct timezone
attributes(dt_read$POSIXct)
#> $class
#> [1] "POSIXct" "POSIXt" 
#> 
#> $tzone
#> [1] "Pacific/Tahiti"
```

On the implementation site, this means that `fst`'s C++ core library now has three additional [`column attributes`](https://github.com/fstpackage/fst/blob/36eaaecc4f5c0f3eb7ab2e0a9f30eb5688573b34/src/fstcore/interface/ifstcolumn.h#L61-L78) (`INT_64_TIME_NANO`, `INT_32_TIME_SECONDS` and `DOUBLE_64_TIME_SECONDS`), indicating a `nanotime`, `POSIXct (integer based)` and `POSIXct (double)` type column.

Thanks a lot for your feedback and comments!

**Comment by MarcusKlik** [comment]
Hi @eddelbuettel, in your package `nanotime`, the following constructor code is used:

``` r
nanotime <- function(x, ...) {
    new("nanotime", as.integer64(x, keep.names=TRUE))
}
```

When I run a benchmark on this, I find:

``` r
# an integer64 vector
x <- bit64::as.integer64(1:125000000)

# Convert 125 million integer64 values to nanotime
microbenchmark::microbenchmark(
  nanotime::nanotime(x),
  times = 1)
#> Unit: seconds
#>                   expr     min      lq    mean  median      uq     max
#>  nanotime::nanotime(x) 3.08293 3.08293 3.08293 3.08293 3.08293 3.08293
#>  neval
#>      1
```
So, the constructor takes about 3 seconds for 1 GB of data. Fast enough for most purposes off course, but in `fst` that was a bottleneck in speed.
To remedy that, I created a custom converter equivalent to:

``` r
Rcpp::sourceCpp(code = '
#include <Rcpp.h>

// [[Rcpp::export]]
SEXP as_nano_integer64(SEXP int64Vec)
{
  SEXP classAttr;
  PROTECT(classAttr = Rf_mkString("nanotime"));
  Rf_setAttrib(classAttr, Rf_mkString("package"), Rf_mkString("nanotime"));

  UNPROTECT(1);
  Rf_classgets(int64Vec, classAttr);

  Rf_setAttrib(int64Vec, Rf_mkString(".S3Class"), Rf_mkString("integer64"));
  SET_S4_OBJECT(int64Vec);

  return int64Vec;
}')
```

This is just a hack to decorate an `integer 64` class with the appropriate `nanotime` metadata (and only works because I know for sure I have an `integer 64` vector). 

The benchmark now reads:

``` r
# Convert 125 million int64 values to nanotime
microbenchmark::microbenchmark(
  as_nano_integer64(x),
  times = 1)
#> Unit: microseconds
#>                  expr    min     lq   mean median     uq    max neval
#>  as_nano_integer64(x) 72.672 72.672 72.672 72.672 72.672 72.672     1
```

That passes my tests but I wanted to check with you that I'm not missing anything. Is my method of just decorating an existing `integer64` vector skipping any crucial steps?
  
thanks a lot & much obliged for all your great work

**Comment by eddelbuettel** [comment]
I'll page Leonardo who was instrumental in the S3/S4 conversion we needed to tighter control over ops.  Some side effect on performance is, sadly, a possible side-effect.

**Comment by MarcusKlik** [comment]
Great, thanks!

**Comment by lsilvest** [comment]
Yes, that should be correct: it avoids the additional copy by working directly on `x`. It does what R's `new` (a `.Call` to `C_new_object` + `initialize`) does without the copy and the `initialize` is not needed in this case. I've quickly tested it and it looks like it's correct. Hopefully there's nothing else that `new` does that I've missed. We'll definitely consider putting it in `nanotime`.

**Comment by MarcusKlik** [comment]
Hi @lsilvest, thanks for taking a look at the code. Then I'll just use this 'decorator' and if anything unexpected turns up, I will let you know!

**Comment by eddelbuettel** [comment]
Awesome.  I was a little worried that this _might_ have nasty side effects, but then again at the end of the day everything is just bloody attributes to a naked `SEXP`.

**Comment by MarcusKlik** [comment]
Indeed! Still not really object-oriented is it :-) Thanks again!
