### ISSUE TITLE
dates are lost when reading from fst

### ISSUE THREAD

**Issue by verajosemanuel** [fstpackage/fst#79]
got a data frame with a date column 

```
str(df$date)
date                       : Date, format: "2016-01-02" "2014-01-02" "2012-01-02" "2017-01-02

fst::write.fst(df,"mydf.fst")
```

saved to fst. When reading again from fst, date column is no more a date column

```
df <- fst::read.fst("mydf.fst")
str(df$date)
 num [1:83860] 1357084800 1357084800 1357084800 1357084800 1357084800 ...
```

The expected behaviour is to preserve formatting and data types.

```

R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base   
attached packages:
[1] fst_0.7.2    bindrcpp_0.2 magrittr_1.5 dplyr_0.7.2  fcuk_0.1.21 
```

**Comment by MarcusKlik** [comment]
Hi @verajosemanuel, thanks for reporting the issue! Indeed, `fst` was not retaining the class attribute for the `Date` type. But this has been fixed in the development version and will be available in the next release.

The dev version will give you:

``` r
df <- data.frame(date = as.Date(c("2016-01-02", "2014-01-02", "2012-01-02", "2017-01-02")))
str(df$date)
#>  Date[1:4], format: "2016-01-02" "2014-01-02" "2012-01-02" "2017-01-02"

fst::fstwrite(df,"mydf.fst")
df_read <- fst::fstread("mydf.fst")
str(df_read$date)
#>  Date[1:4], format: "2016-01-02" "2014-01-02" "2012-01-02" "2017-01-02"
```

You can install the dev version using

```r
devtools::install_github("fstpackage/fst", ref = "develop")
```

Note: the above example creates a date column which has a real vector as it's base, but the column read after the `fstwrite` / `fstread`  cycle is an integer vector:

``` r
typeof(df$date)
#> [1] "double"

typeof(df_read$date)
#> [1] "integer"
```

This is because `fst` converts all `Date` types to integer to increase performance of `Date` type serialization (an integer can be compressed much more efficiently than a double).

Hope this helps you until the next CRAN release!

**Comment by MarcusKlik** [comment]
Hi @verajosemanuel, thanks again for reporting the issue, the `Date` type has now been implemented in the `dev` vesion of `fst`.
