### ISSUE TITLE
Stack imbalance warnings & instability with Develop version

### ISSUE THREAD

**Issue by ryankennedyio** [fstpackage/fst#86]
Hi,

Since moving to the develop branch of FST we've been noting instability (unfortunately often very hard to reproduce). I am not sure if this could be to do with the transition process of an old version of FST to the latest, but any info about where warnings come from would be appreciated.

One example of the warnings;
```
Warning: stack imbalance in '.Call', 30 then 29
Warning: stack imbalance in '{', 27 then 26
Warning: stack imbalance in '{', 22 then 21
Warning: stack imbalance in '<-', 18 then 17
Warning: stack imbalance in '{', 15 then 14
Warning: stack imbalance in '.Call', 20 then 19
Warning: stack imbalance in '{', 17 then 16
Warning: stack imbalance in '{', 12 then 11
Warning: stack imbalance in '.Call', 19 then 18
```

Another example of a non-reproducible issue:
```
> files.in<- c("agg-master.fst", "agg-master-mega.fst",
              "agg-master-large.fst", "agg-master-mid.fst",
              "agg-master-small.fst", "agg-master-micro.fst",
              "agg-master-largeplus.fst","agg-master-midplus.fst",
              "agg-master-smallplus.fst"
 )
> 
> lapply(1:length(files.in), function(x) chopLastNYears(inputDir, files.in[x], outputDir, 3))
```

gave us this error once, but not when running with only one input
```
Error in lapply(1:length(files.in), function(x) chopLastNYears(inputDir,  : 
 SET_VECTOR_ELT() can only be applied to a 'list', not a 'character'
```

For what it's worth, we write all FST files to a network drive, usually with some compression. The filesize is between 500MB and 50GB, mostly around 1-2GB.

I also note that we have a large number of files that give us the warning 
```In fstretrieve(fileName, columns, from, to) :
  This fst file was created with a beta version of the fst package. Please re-write the data as this format will not be supported in future releases.
```
Of course we need to re-write these files, but could this be causing some of the current issues? I.e. another error sometimes received is to do with (sorry cannot remember verbatim or reproduce), `bad header: could not read header type` or similar. I am quite sure this happens when writing to disk with one version of FST and reading with a more recent version.

I should also say that we do expect some of this on the develop branch, but the Master branch is too far behind in terms of feature implementation to be used (and Master is actually less stable when working with very large files).

**Comment by ryankennedyio** [comment]
Here is an example, again not easily reproducible:

```
Error in fstretrieve(fileName, columns, from, to) : 
  Error reading file header, your fst file is incomplete or damaged
```

I have no troubles reading from, or writing to this file, however my colleague gets this error each time, and we've both confirmed we have exactly the same version of fst installed

**Comment by MarcusKlik** [comment]
Hi @ryankennedyio, thanks for reporting and working with the `dev` version of `fst`. 

> Warning: stack imbalance in '.Call', 30 then 29

This warning is due to an unmatched pair of `PROTECT` and `UNPROTECT` macro's (R API) in C++. I'll have to sort through the new code using that API to find that unmatched pair.

> This fst file was created with a beta version of the fst package. Please re-write the data as this format will not be supported in future releases.

Yes, reading `fst` files created with the CRAN version will generate this warning. The reason is that the current CRAN version uses a format that is not very robust against tampering with the format or loss of data (these can create unpredictable crashes). In the dev version much has been done to make the format more stable, e.q. hashing of headers and data, protection against IO errors etc. I would like users to switch to an updated `fst` format when the next version is on CRAN.

> SET_VECTOR_ELT() can only be applied to a 'list', not a 'character'

I'm afraid this error will be hard to pinpoint without a reproducible example. The `SET_VECTOR_ELT` is used quite a lot in the package C++ code...

>  Error reading file header, your fst file is incomplete or damaged

There are two reasons why this error could occur (in [this code](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/fststore.cpp#L120-L124) or[this code](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/fststore.cpp#L489-L493)). The first error is thrown when a file can't be properly read after it is opened, perhaps due to access rights? The second error is thrown when the 64 bit hash value of the header information doesn't check out. Calculation of the hash value was changed a few days ago. Reading a file that was generated with a `fst` dev version before that commit will generate that error (hash calculation has changed so the 'old' value will be different).

I'm sorry you are hitting these warnings and errors and I will try to find a solution as soon as possible where I can! To distinguish between these last two errors, I'll make sure they throw errors with a different message. As for the other problems, those will probably take longer to find so if you have any additional information or smaller (:-)) reproducible examples, please let me know.

Thanks for taking the time to report!

**Comment by ryankennedyio** [comment]
Hi @MarcusKlik 

`RE Cran`:  This sounds good. We are going through the process now of re-writing all source files (we have quite a few). We're now working from a particular SHA commit code from develop in lieu of a recent version release on Master.

`RE SET_VECTOR_ELT()`: I managed to get the same issue again this morning (a few times). Here was the code to trigger the issue (though again not exactly perfectly reproducible);
```
lapply(dir(), function(fname){
  if(grepl('.fst', fname)){
    dt <- read.fst(fname, as.data.table = T)
    write.fst(dt, fname, compress = 50)
  }
  return(fname)
})
```
There are about 50 ~1GB files in this directory, and a few which 5-10GB, and a single ~30GB one 

`RE Hash Version`:  Thank you for confirming. This was solved when we ensure everything is up to date on `dev` branch.


I guess the only other comment would be that displaying the filename that causes an error would be helpful. Thanks again for the help, this package is brilliant.

**Comment by MarcusKlik** [comment]
Hi @ryankennedyio , I will update the error messages to reflect the relevant file and whether a read or write operation is causing the error.  That way, you get better feedback on where exactly errors are produced.

Your code should be fine as long as you are reading from the CRAN version of `fst`. But after your files are overwritten, you can't do the same at a later stage for updating to yet a new development version of `fst`, is that a problem for you?

(so the dev version supports reading from an old CRAN version, but not from a previous dev version...)

**Comment by ryankennedyio** [comment]
That would be very helpful

That does make sense (RE reading/writing with different dev versions -- essentially the version on CRAN is the only one which is guaranteed able to be read by future FST versions?), but we found ourselves needing to use a develop branch for writing in order to work around https://github.com/fstpackage/fst/issues/46.

Would you happen to know of a particular SHA commit which solves #46 when writing, and will be able to be read by future versions of `fst` ?

**Comment by MarcusKlik** [comment]
Hi @ryankennedyio, I can see how that is a problem for you: you can't use the CRAN version because of #46 and the `fst` format of the dev version is not guaranteed to remain stable with new commits.

That will remain a problem until the next release branch is created. I have labelled all feature request requiring a format change with the [_format_](https://github.com/fstpackage/fst/labels/format) label. Although most of these features will not be implemented in the next release, I will make sure that the format is prepared for them to be implemented later (for example, hashing data blocks requires an additional meta-data field for each data block containing the hash value. I can prepare the format for that without actually implementing the code yet.).

To give you a time-line, I hope to have the format ready in a week or two. Then I will create a release branch and declare the format as stable. After that point in time, the format won't change anymore between commits, and you'll have your 'stable' dev version.

Hope you can wait that long!

**Comment by ryankennedyio** [comment]
@MarcusKlik That would be amazing. Great stuff.

**Comment by ryankennedyio** [comment]
Hi @MarcusKlik 

Sorry to be a pain -- just checking to see if any of the commits to Develop branch since last posting in this thread appropriate to use as a stable version?

Thanks

**Comment by MarcusKlik** [comment]
Hi @ryankennedyio, no problem! The format is stable now with the latest `dev` commits. I had to fix some 8-byte boundary alignment problems that gave warnings on CRAN with the ASAN and UBSAN tests ( C++ memory sanitizers). These warnings have been solved now but required a change in the offset of some parameters in the format.

But I'm not going to change the format anymore, so you should be safe!

Off course, when you want to be 100 percent safe, it's better to wait until the next CRAN release, after that, the format will be kept backwards compatible over CRAN versions...

**Comment by ryankennedyio** [comment]
@MarcusKlik brilliant. We'll lock onto this latest one for now until the next CRAN release, and then rebuild anything that needs rebuilding once that is publicly available.

Thanks again! (Feel free to mark closed if stack imbalance warning is now gone -- other issue w/  instability was clearly result of different formats between commits in develop)

**Comment by MarcusKlik** [comment]
Thanks for reporting, I will close the issue then!
