### ISSUE TITLE
R session crashing after fst write - tips for debugging?

### ISSUE THREAD

**Issue by treysp** [fstpackage/fst#89]
This package is fantastic - thanks so much for all your work on it!

I'm using the CRAN fst version (0.7.2) on a Windows 7 OS, and my R session is intermittently and unpredictably crashing at the conclusion of an fst write operation (that sometimes completes and other times not). I normally work in RStudio, but I have observed it in base R as well. 

It is irritatingly unreproducible - sometimes I will execute hundreds of fst read/writes over days before it occurs, and other times it happens with every write attempt. Sometimes I will reboot my machine and it goes away, other times it doesn't seem to matter.

I'm reaching out to ask how I can best get log information that would shed more light on why this is happening. I've checked the [RStudio logs](https://support.rstudio.com/hc/en-us/articles/200554756-RStudio-Application-Logs), but there doesn't appear to be anything useful there. 

Is there a version of backtrace or some other utility that would help me track this down so I can either fix my setup or notify the developers of whichever software component is causing the issue? Thanks!

**Comment by MarcusKlik** [comment]
Hi @treysp, thanks a lot!

Your crashes are very unfortunate, but since the CRAN release v0.7.2 a lot of problems have been solved, so there is a reasonable chance that the `dev` version will not have the same issues.

Would you mind testing your write operations with the `dev` version of the `fst` package?

```r
devtools::install_github("fstpackage/fst", ref = "develop")
```

If you could manage a reproducible example, I could locate the problem by debugging the `fstcore` C++ library, but from your remarks I can see that's probably not so easy. To rule out problems caused by `RStudio` (not very likely),  you could try to run the script from the R command line tool.

`fst` could probably use a `verbose = TRUE` option for `fstread` and `fstwrite` operations (like `data.table`'s `fread` method). That way, we could get relevant information more quickly.

I hope the `dev` version solves the crashes, if not I would be much obliged with any additional information you could provide!

**Comment by treysp** [comment]
I haven't had a chance to test out the dev version yet (it will result in file types that aren't compatible with v0.7.2, correct?), but I wanted to pass along the Windows Event log for the crash in case it's useful. 

I'm doing some standard debugging steps (checking system files for corruption, reinstalling R and RStudio, etc.), and will report back as I accrue new information. Thanks!

    Faulting application name: rsession.exe, version: 1.0.153.0, time stamp: 0x59693291
    Faulting module name: fst.dll, version: 0.0.0.0, time stamp: 0x595c7778
    Exception code: 0xc0000005
    Fault offset: 0x000000000000f2f8
    Faulting process id: 0x27e8
    Faulting application start time: 0x01d33ba877c76af8
    Faulting application path: C:\Program Files\RStudio\bin\x64\rsession.exe
    Faulting module path: C:\R_packages\fst\libs\x64\fst.dll

**Comment by MarcusKlik** [comment]
Hi @treysp, indeed, at this point files produced with a  `dev` version will possibly give problems when read from a later `dev` version. That's because a lot of format changes have been introduced to facilitate additional options in the C++ `fstcore` library (data- and header hashes, key indexes, movable header blocks, encryption, additional column types, column attributes, column scales and multi-chunk `fst` files are a few examples that have been introduced after v0.7.2).

Your log indicates that the problem is indeed caused by a crash in code from the `fst` package dll, but it's hard to say anything more than that. I hope your problem is solved in the latest version, any new information is much appreciated.

thanks for reporting!

**Comment by treysp** [comment]
I'm not turning up much of use on my end, so I'll go ahead and close this issue. If I end up discovering something useful, I'll reopen and comment.

Thanks again for all your work on this fantastic package!

**Comment by MarcusKlik** [comment]
And thanks for reporting!
