### ISSUE TITLE
error STRING_ELT() can only be applied to a 'character vector', not a 'NULL' in saving fst files

### ISSUE THREAD

**Issue by wei-wu-nyc** [fstpackage/fst#90]
I am getting following message:
Error in fstStore(normalizePath(path, mustWork = FALSE), x, as.integer(compress)) :
  STRING_ELT() can only be applied to a 'character vector', not a 'NULL'
I am using R 3.3.1. The fst develop version.
I have been using this set up for months with no problem.
Don't know which part can cause this error. Just want some clues before dig in deeper.
Thanks.

**Comment by MarcusKlik** [comment]
Hi @wei-wu-nyc, thanks for reporting your problem. Do I understand correctly that you are suddenly getting this error on the `dev` version from 2 months ago where you didn't have errors before?

I'm asking because usually this error indicates that you are trying to read a `fst` file that was produced with an 'older' `dev` version. If that is the case, re-saving the `fst` file is your only option at the moment.

I can see that the format changes between `dev` versions poses a problem for people when they update their `dev` version. After the next CRAN release, the `fst` file format will be stable and you won't have these problems anymore or a clear warning will be given when reading from a incompatible (`dev`) version.

Reading from a `fst` file generated with a CRAN version of the package is always supported. But backwards compatibility between `dev` version would introduce many additional branches in the code which would be very hard to maintain. With a stable format, we won't have these problems anymore.

If you have a reproducible example that induces your error, that would be great!

**Comment by wei-wu-nyc** [comment]
@MarcusKlik I can't reproduce this problem, because after this problem I have tried to remove and install different versions of fst packages to see which works. Now I think it is a problem related with a previous bug I reported and fixed, but it seems to come back. I will update the issue in that thread. I think we can close this bug, and we should re-open the other bug.

**Comment by MarcusKlik** [comment]
Hi @wei-wu-nyc, good idea and thanks for testing!

**Comment by tedmoorman** [comment]
I encountered this issue when I ran the <read_fst()> and <write_fst()> functions preceded by <fst::>. When I added <require(fst)> before running the functions, the error went away.

**Comment by MarcusKlik** [comment]
Hi @tedmoorman, thanks for reporting!

Are you using a develop version of `fst` as indicated in the package startup message?

If not, your finding is a bit puzzling because there is no real difference between first attaching `fst` by using `require()` or `library()` before using `write_fst()` as compared to using `fst::write_fst()` directly (except for the startup message defined in [`.onAttach()`](https://github.com/fstpackage/fst/blob/develop/R/onAttach.R#L23-L48)).

**Comment by tedmoorman** [comment]
Hi @MarcusKlik, thank you for responding. I haven't experienced this recently, and an updated version of fst may have been installed. The package is fantastic! Thank you for your great work!
