### ISSUE TITLE
compress = 100 crashes 

### ISSUE THREAD

**Issue by xiaodaigh** [fstpackage/fst#92]
I am running RStudio and R 3.4.1 on Windows 10 Pro 64bit. 

Running the below code always crashes Rstudio and when I load the file using `read.fst` it gives error
```
Error in fstRead(fileName, columns, from, to) : 
  Unknown type found in column.
Timing stopped at: 0.01 0 0.01
```

I can compress = 0 and it will run fine, it's just when I do compress = 100 that it fails. Also the data is quite big so it's taking up most of RAM, could this be caused by compress =100 trying to use more RAM than available?

```
library(data.table)

#require(data.table)
#' Generate Synthetic dat
#' @import data.table
gen_datatable_synthetic <- function(N=2e9/8, K=100) {
  data.table(
    id1 = sample(sprintf("id%03d",1:K), N, TRUE),      # large groups (char)
    id2 = sample(sprintf("id%03d",1:K), N, TRUE),      # large groups (char)
    id3 = sample(sprintf("id%010d",1:(N/K)), N, TRUE), # small groups (char)
    id4 = sample(K, N, TRUE),                          # large groups (int)
    id5 = sample(K, N, TRUE),                          # large groups (int)
    id6 = sample(N/K, N, TRUE),                        # small groups (int)
    v1 =  sample(5, N, TRUE),                          # int in range [1,5]
    v2 =  sample(5, N, TRUE),                          # int in range [1,5]
    v3 =  sample(round(runif(100,max=100),4), N, TRUE) # numeric e.g. 23.5749
  )
}

res <- NULL
res <- c(res, list(system.time(DT <- gen_datatable_synthetic())))
system.time(fst::write.fst(DT,file.path(data_path, "DT100.fst"), compress=100))
```

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, thanks for reporting your issue. Are you using the CRAN v0.7.2 version of `fst` or the development version?

The reason I ask is that similar issues have been reported earlier with the CRAN version, if you could re-test with the latest dev that would be great!

( I didn't get any errors running your code, but I'm using less rows for testing)

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, to see if I could reproduce your error, I performed the following benchmarks:

``` r
library(data.table)
library(microbenchmark)
library(fst)

# generate synthetic data
gen_datatable_synthetic <- function(N, K = 100) {
  data.table::data.table(
    id1 = sample(sprintf("id%03d",1:K), N, TRUE),      # large groups (char)
    id2 = sample(sprintf("id%03d",1:K), N, TRUE),      # large groups (char)
    id3 = sample(sprintf("id%010d",1:(N/K)), N, TRUE), # small groups (char)
    id4 = sample(K, N, TRUE),                          # large groups (int)
    id5 = sample(K, N, TRUE),                          # large groups (int)
    id6 = sample(N/K, N, TRUE),                        # small groups (int)
    v1 =  sample(5, N, TRUE),                          # int in range [1,5]
    v2 =  sample(5, N, TRUE),                          # int in range [1,5]
    v3 =  sample(round(runif(100,max=100),4), N, TRUE) # numeric e.g. 23.5749
  )
}

# display column types
dt <- gen_datatable_synthetic(1)
sapply(colnames(dt), function(x) typeof(dt[[x]]))
#>         id1         id2         id3         id4         id5         id6 
#> "character" "character" "character"   "integer"   "integer"    "double" 
#>          v1          v2          v3 
#>   "integer"   "integer"    "double"


bench_write <- function(nr_of_rows, iterations, compression, generator) {
  # write benchmark
  res <- NULL
  for (count in 1:iterations) {
    # generate unique table with nr_of_rows rows
    dt <- generator(nr_of_rows)

    # get SSD out of it's sleep before starting benchmark
    saveRDS("warmup", "warmupdisk.rds")

    # perform a single run only to avoid disk caching
    # (disk caching will lead to overestimation of speeds)
    bench <- microbenchmark(
      fst::fstwrite(dt, "1.fst", compress = compression),
      times = 1)

    res <- rbindlist(list(res, data.table(
      Compression = compression,
      ObjectSize = as.numeric(object.size(dt)),
      Time = bench$time,
      Ratio = as.numeric(file.size("1.fst") / object.size(dt)))))
  }

  res[, list(
    Speed = 1e3 * median(ObjectSize / Time),
    Ratio = median(Ratio)), by = "Compression,ObjectSize"]
}


# let fst use 4 threads
fstsetthreads(4)
#> [1] 4

# Median compression speed (MB/s) and ratio at maximum compression
bench_write(25e6, 8, 100, gen_datatable_synthetic)
#>   Compression ObjectSize   Speed     Ratio
#> 1:         100 1314012120 86.1775 0.2784841

# Median compression speed (MB/s) and ratio at average compression
bench_write(25e6, 8, 50, gen_datatable_synthetic)
#>    Compression ObjectSize    Speed    Ratio
#> 1:          50 1314012120 303.0664 0.671564

# Median compression speed (MB/s) and ratio at low compression
bench_write(25e6, 8, 1, gen_datatable_synthetic)
#>    Compression ObjectSize   Speed    Ratio
#> 1:           1 1314012120 324.732 1.178896
```

A few remarks on the benchmarks:

* Before each measurement, I store a very small file to 'wake up' the disk. That's to make sure we're not measuring any disk startup-time
* I'm using each generated dataset only once. I you re-write an identical dataset to disk a second time, benchmark speeds can go up significantly because of (hardware) disk caching. 
* Measurements using the `microbenchmark` package are much more accurate than measurements using `system.time`.
* The compression ratio for the `compress = 1` setting is higher than 1. So, the on-disk file is larger than the in-memory table. I'm not sure at this point why this is the case, apparently strings are stored more compactly in `R` than in `fst` or `fst` has relatively more metadata.

As you can see, there are only 25 million rows in the dataset used, a factor 10 less than in your example (I currently only have access to my laptop). To test larger columns, I did a benchmark on your _id4_ column with 250 million rows (like in your example):

``` r
# single integer table
int_table <- function(nr_of_rows) {
  data.table(
    id4 = sample(100, nr_of_rows, TRUE))
}

# Median compression speed (MB/s) and ratio at high compression
bench_write(250e6, 10, 100, int_table)
#>    Compression ObjectSize    Speed     Ratio
#>1:         100 1000001072 1201.378 0.2120367

# Median compression speed (MB/s) and ratio at average compression
bench_write(250e6, 10, 50, int_table)
#>    Compression ObjectSize    Speed     Ratio
#> 1:          50 1000001072 3353.286 0.2548218

# Median compression speed (MB/s) and ratio at low compression
bench_write(250e6, 10, 1, int_table)
#>    Compression ObjectSize    Speed     Ratio
#> 1:           1 1000001072 904.8402 0.9855828
```

The `dev` version runs without problems. Please note the extreme speed for the `fstwrite` at a compression setting of 50 (around 3.3 GB/s). At that point `fst` finds a nice balance between compression ratio (0.25) and compression speed (with 4 cores). The result is a write speed higher than the disks maximum speed (which is ~2 GB/s).

With your dataset this effect is not visible because the `character` columns currently have comparatively low performance as they are not run in parallel yet (all other types are). 

Hope you can use this code to benefit your benchmarks! If you still see the error on the `dev` version, please let me know!

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, are you still experiencing these problems on the latest `dev` version? I didn't get any errors on the code you posted on `Win 10` and `Ubuntu 16.04` using the latest `fst`, which OS are you running?

thanks!

**Comment by xiaodaigh** [comment]
I can't seem to build fst on my Windows 10. I got the below error

```
fst 0.7.3 IN DEVELOPMENT built 2017-11-14 10:40:20 UTC
Error: package or namespace load failed for ‘fst’:
 .onAttach failed in attachNamespace() for 'fst', details:
  call: hasopenmp()
  error: object '_fst_hasopenmp' not found
```

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, yes, sometimes you get that error when you have the CRAN version installed and try to build the `dev` version (see also #97). Could you try to de-install the CRAN version first and then  build the `dev` version?

Thanks for testing!

**Comment by xiaodaigh** [comment]
@MarcusKlik No, thank you. 

Yes it no longers gives me an error! It seems fixed. Sorry I should asked earlier I had tried to build it afew times with the same error.

**Comment by xiaodaigh** [comment]
Not sure if ti's to do with fst but the timings look odd. _Elapsed_ is smaller than _user_
```r
 system.time(fst::write.fst(DT,file.path(data_path, "DT100.fst"), compress=100))
   user  system elapsed 
 181.78   26.30  158.53 
```

**Comment by MarcusKlik** [comment]
That's very odd indeed! Looks like the system is spending negative time (that's a great computer you have there :-)).

On my system something similar is occurring:

``` r
#sample data set
dt <- data.frame(X = 1:250000000)

timings <- system.time(fst::write_fst(dt, "1.fst", 100))

# system timings
print(timings)
#>    user  system elapsed 
#>    2.04    0.06    0.55 

# speed (MB/s) based on elapsed time
1e-6 * as.numeric(object.size(dt)) / timings[["elapsed"]]
#> [1] 1818.183
```

I suspect the readings are off because `fst` is wrtiting to disk with multiple-threads. So perhaps these system timings are not very accurate. Usually, I go with the `microbenchmark` package:

``` r
timings <- microbenchmark::microbenchmark(
  system.time(fst::write_fst(dt, "1.fst", 100)),
  times = 1
)

# system timings
print(timings)
#> Unit: milliseconds
#>                                           expr      min       lq     mean
#>  system.time(fst::write_fst(dt, "1.fst", 100)) 661.684 661.684 661.684
#>    median       uq      max neval
#>  661.684 661.684 661.684     1

# speed (MB/s) based on elapsed time
1000 * as.numeric(object.size(dt)) / timings$time
#> [1] 1511.296
```

And just a _manual_ check:

``` r
t0 <- Sys.time()
fst::write_fst(dt, "1.fst", 100)
t1 <- Sys.time()

print(t1 - t0)
#> Time difference of 0.7220218 secs
```

that's about the same as the time measured with `microbenchmark`.
I guess the _user_ time reported is actually the total time that the user spends on all threads!
