### ISSUE TITLE
error: object '_fst_hasopenmp' not found while loading devel version.

### ISSUE THREAD

**Issue by arunsrinivasan** [fstpackage/fst#97]
Just installed `fst` development version to test performance improvements due to OpenMP, and got this:

```r
require(fst)
# Loading required package: fst
# fst 0.7.3 IN DEVELOPMENT built 2017-10-26 14:43:12 UTC
# Error : .onAttach failed in attachNamespace() for 'fst', details:
#   call: hasopenmp()
#   error: object '_fst_hasopenmp' not found
```

```r
sessionInfo()
# R version 3.3.2 (2016-10-31)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows Server >= 2012 x64 (build 9200)

# locale:
# [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    
# LC_MONETARY=English_United States.1252
# [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     

# loaded via a namespace (and not attached):
# [1] parallel_3.3.2 tools_3.3.2    yaml_2.1.14    Rcpp_0.12.9    fst_0.7.3     
```

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, that's a curious error message, looks like `R` is still looking at old namespace definitions. If I install with:

```r
devtools::install_github("fstpackage/fst", ref = "develop")
```

everything looks fine on Windows and Ubuntu on my laptop (note that the `dev` version is on the `develop` branch, in contrary to `data.table`'s `dev` version). Also, [the Travis builds](https://travis-ci.org/fstpackage/fst) seem to run without problems (the two OSX fails are due to the missing OpenMP support, same problem as with the `data.table` package :-)).

Could it be a windows server thing? Or perhaps sometimes when you are building on top of an old build, the build doesn't remove all _.o_ files, did you do a fresh install or clone to an empty directory?

You could also try first removing the CRAN package before installing the `dev` version.

Hope that will work for you, please let me know if the problem persists!

**Comment by arunsrinivasan** [comment]
Hi Mark, 

> You could also try first removing the CRAN package before installing the dev version.

This did it. Thank you for the quick reply!
