### ISSUE TITLE
Attributes for POSIXct type columns

### ISSUE THREAD

**Issue by arunsrinivasan** [fstpackage/fst#98]
Hi again, Mark,

```r
require(fst)
df <- data.frame(x=as.POSIXct("2017-05-05 10:20:30", tz="America/New_York"))
df
#                     x
# 1 2017-05-05 10:20:30
attributes(df$x)
# $class
# [1] "POSIXct" "POSIXt" 
# $tzone
# [1] "America/New_York"

f <- tempfile()
write.fst(df, f)
ans <- read.fst(f)
ans$x
# [1] 1493994030
attributes(ans$x)
# NULL
```

It'd be great to have attributes restored for POSIXct types.

**Comment by MarcusKlik** [comment]
Hi again @arunsrinivasan!

in the `dev` version a lot of attributes have been added to the format, also `POSIXct`:

``` r
df <- data.frame(x = as.POSIXct("2017-05-05 10:20:30", tz="America/New_York"))
attributes(df$x)
#> $class
#> [1] "POSIXct" "POSIXt" 
#> 
#> $tzone
#> [1] "America/New_York"

f <- tempfile()
fst::write_fst(df, f)
ans <- fst::read_fst(f)

attributes(ans$x)
#> $class
#> [1] "POSIXct" "POSIXt" 
#> 
#> $tzone
#> [1] "America/New_York"
```

adding the time-zone correctly was quite a struggle, because there is no consistent cross-language definition for that. In the end, being able to add time-zones was the sole reason for allowing a single custom `string` (annotation) to be added to each column. In the case of `POSIXct`, that `string` can be used for a custom time-zone.

In the `R` wrapper code, a `POSIXct` vector is created [here](https://github.com/fstpackage/fst/blob/develop/src/fsttable.cpp#L153-L161). As you can see, the annotation is set to the time-zone string.

(as of yet, no other types require an annotation, but at least the solution is scalable now :-)

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, in issue #82, a code example is included that shows all currently supported column types. For the `date` and `time` types, both the `integer` and `double` types are supported (that's a different approach then `feather` takes, because in `feather` the `double` based types are converted to 64-bit `integers`. I believe both `integer` and `double` based types are valid representations and it should be up to the user which is appropriate).

thanks!
Mark

**Comment by arunsrinivasan** [comment]
Brilliant!

There seems to be an edge case though. It'd be great to take care of it to ensure `identical`-ness to rda.

```r
require(fst) # devel
df <- data.frame(x=Sys.time())
attributes(df$x)$tzone <- "" 
attributes(df$x)
# $class 
# [1] "POSIXct" "POSIXt"
# $tzone
# [1] ""

f <- tempfile()
write_fst(df, f)
attributes(read_fst(f)$x)
# $class
# [1] "POSIXct" "POSIXt"
```

The `tzone` attribute, even if empty, could be retained, so that it is *identical* to the result returned by `rda`.

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, yes an empty time-zone should be retained. That shouldn't be too hard to fix, will do that as soon as possible, thanks for spotting that!

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, the latest `dev` now retains an empty timezone string. Also, I [added](https://github.com/fstpackage/fst/commit/9d49346765e58e683550d02b8c3da0c227656c9e) a unit test with your reproducible example, thanks for submitting!

**Comment by arunsrinivasan** [comment]
Thanks for the quick fix. But now, I get another issue (which I think is due to this fix):

```r
require(fst) # built 2017-10-31
require(data.table)
dt <- data.table(x=Sys.time())
dt
#                      x
# 1: 2017-10-31 08:50:05
dt$x
# [1] "2017-10-31 08:50:05 EDT"

attributes(dt$x)
# $class
# [1] "POSIXct" "POSIXt" 
# 

f <- tempfile()
write_fst(dt, f)
ans <- read_fst(f)
ans
#                     x
# 1 2017-10-31 12:50:05
ans$x
# [1] "2017-10-31 12:50:05 UTC"

attributes(ans$x)
# $class
# [1] "POSIXct" "POSIXt" 

# $tzone
# [1] "UTC"
```

The `tzone` attribute needs to be set only if it existed while writing to a `fst` file. And if it was set, but to an empty string, `""`, then it needs to be set to the same empty value. I think then this issue would be taken care of as well.

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, the solution I chose is taken from the description in the `R` documentation [here](https://stat.ethz.ch/R-manual/R-devel/library/base/html/strptime.html).

> A character string specifying the time zone to be used for the conversion. System-specific  but "" is the current time zone, and "GMT" is UTC. Invalid values are most commonly treated as UTC, on some platforms with a warning.

So,the idea was that a `NULL` as the `tzone` attribute is basically invalid and should be treated as `UTC`. I see that the `feather` package does the same (see [this code](https://github.com/wesm/feather/blob/master/R/src/feather-write.cpp#L332-L346)).

But I agree with you that `fst` should not make any decisions like that for the user and it's probably better to retain a `NULL` attribute :smile: 

thanks for testing that further!

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, a `POSIXct` column without a `tzone` attribute [is now correctly retained](https://github.com/fstpackage/fst/blob/71178e9446b4f9d8c78637ac9dca811e1956cb29/src/fst_table.cpp#L221-L235) after a `read_fst` / `write_fst` cycle. Indeed, I share your idea that such a cycle should have a result identical to a `saveRDS` / `readRDS` cycle and that `fst` shouldn't make the decision to add a `tzone` attribute where there was none before.

And the same now holds for an `integer`-based `POSIXct` type, thanks a lot!

**Comment by arunsrinivasan** [comment]
@MarcusKlik thank you very much!
